package net.tecnihardcore;

import net.fabricmc.fabric.api.client.networking.v1.*;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.rendering.v1.*;
import net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.render.*;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.client.sound.PositionedSoundInstance;
import net.minecraft.client.sound.MovingSoundInstance;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.sound.*;
import net.minecraft.world.Heightmap;
import net.minecraft.text.Text;
import net.minecraft.util.math.*;
import com.mojang.blaze3d.systems.RenderSystem;
import java.util.*;
import java.nio.file.*;

/** Deterministic geometry, bounded cosmetic particles, essential telegraphs never culled by particle options. */
public final class CataclysmVisuals {
    private static final class Visual {UUID id;int type,radius,age,duration,state,width,destruction;BlockPos center;Vec3d position,previous;double crownY,previousCrown;long received;List<Vec3d> marks;}
    private static final Map<UUID,Visual> active=new LinkedHashMap<>();private static Object world;public static boolean shake=true;
    private static final Map<UUID,StormSound> sounds=new HashMap<>();private static boolean shaders;
    private static final VertexConsumerProvider.Immediate GEOMETRY=geometryBuffers();
    private static VertexConsumerProvider.Immediate geometryBuffers(){var fixed=new LinkedHashMap<RenderLayer,BufferBuilder>();fixed.put(RenderLayer.getLines(),new BufferBuilder(8192));return VertexConsumerProvider.immediate(fixed,new BufferBuilder(65536));}
    private static final class StormSound extends MovingSoundInstance {
        private final UUID id;private final boolean warning;
        StormSound(Visual v){super(RegistriesSound.event(age(v)<200?"disaster.alarm":v.type==0?"disaster.wind":v.type==1?"disaster.quake":v.type==2?"disaster.rain":v.type==4?"disaster.wind":"disaster.storm"),SoundCategory.WEATHER,net.minecraft.util.math.random.Random.create());id=v.id;warning=age(v)<200;repeat=true;repeatDelay=0;volume=.01F;}
        @Override public void tick(){Visual v=active.get(id);var client=MinecraftClient.getInstance();if(v==null||client.player==null||client.world==null||(age(v)<200)!=warning){setDone();return;}double t=age(v);Vec3d center=position(v,t),listener=client.gameRenderer.getCamera().getPos(),direction=center.subtract(listener);double distance=direction.horizontalLength();Vec3d source=listener.add(direction.normalize().multiply(Math.min(3,direction.length())));x=source.x;y=source.y;z=source.z;float fade=warning?1:(float)Math.max(0,Math.min(1,Math.min((t-200)/30,(v.duration+60-t)/60)));volume=fade*(float)Math.max(0,Math.min(1,(v.radius+32-distance)/40))*(warning?.8F:v.type==1?.95F:.82F);if(v.type==2&&acid()<.2F)volume*=.3F;}
    }
    private static void clear(){var manager=MinecraftClient.getInstance().getSoundManager();for(var sound:sounds.values())manager.stop(sound);sounds.clear();active.clear();}
    private static double age(Visual v){var w=MinecraftClient.getInstance().world;return v.age+(w==null?0:w.getTime()-v.received);}
    private static double blend(Visual v,double age){return Math.max(0,Math.min(1,(age-v.age)/10));}
    private static Vec3d position(Visual v,double age){return v.previous.lerp(v.position,blend(v,age));}
    private static double crown(Visual v,double age){return v.previousCrown+(v.crownY-v.previousCrown)*blend(v,age);}
    public static void init(){
        StormLayers.init();
        net.fabricmc.fabric.api.client.particle.v1.ParticleFactoryRegistry.getInstance().register(Cataclysms.ACID_DROP,AcidDrop.Factory::new);
        var c=MinecraftClient.getInstance();Path preference=c.runDirectory.toPath().resolve("config/tecnihardcore-shake.txt");try{if(Files.exists(preference))shake=Boolean.parseBoolean(Files.readString(preference).trim());}catch(Exception ignored){}
        ClientCommandRegistrationCallback.EVENT.register((d,r)->d.register(net.fabricmc.fabric.api.client.command.v2.ClientCommandManager.literal("tecni-sacudida").executes(ctx->{shake=!shake;try{Files.writeString(preference,Boolean.toString(shake));}catch(Exception ignored){}ctx.getSource().sendFeedback(Text.literal("Sacudida: "+(shake?"activada":"desactivada")));return 1;})));
        ClientPlayNetworking.registerGlobalReceiver(Cataclysms.CHANNEL,(client,h,b,r)->{var v=new Visual();v.id=b.readUuid();v.type=b.readUnsignedByte();v.center=b.readBlockPos();v.radius=b.readVarInt();v.age=b.readVarInt();v.duration=b.readVarInt();v.width=b.readVarInt();v.destruction=b.readUnsignedByte();v.state=b.readUnsignedByte();v.position=new Vec3d(b.readDouble(),b.readDouble(),b.readDouble());v.crownY=b.readDouble();int count=b.readVarInt();if(v.type>4||v.radius<32||v.radius>512||v.width<40||v.width>600||v.destruction>WeatherRules.maxDestruction(v.type)||!Double.isFinite(v.position.x)||!Double.isFinite(v.position.y)||!Double.isFinite(v.position.z)||!Double.isFinite(v.crownY)||v.crownY-v.position.y<199||v.crownY-v.position.y>1000||count<0||count>8)return;v.marks=new ArrayList<>();for(int i=0;i<count;i++)v.marks.add(new Vec3d(b.readDouble(),b.readDouble(),b.readDouble()));client.execute(()->{if(client.world==null)return;if(v.state==2)active.remove(v.id);else{var old=active.get(v.id);v.previous=old==null?v.position:position(old,age(old));v.previousCrown=old==null?v.crownY:crown(old,age(old));v.received=client.world.getTime();active.put(v.id,v);if(v.state==3)for(var p:v.marks)client.world.playSound(p.x,p.y,p.z,RegistriesSound.event(v.type==3?"disaster.thunder":"disaster.impact"),SoundCategory.WEATHER,1.25F,1,false);}});});
        ClientPlayConnectionEvents.DISCONNECT.register((h,client)->{clear();world=null;});
        ClientTickEvents.END_CLIENT_TICK.register(CataclysmVisuals::tick);
        WorldRenderEvents.END.register(ctx->{var client=MinecraftClient.getInstance();if(client.world==null)return;client.getFramebuffer().beginWrite(false);var m=ctx.matrixStack();Vec3d eye=ctx.camera().getPos();m.push();m.translate(-eye.x,-eye.y,-eye.z);var vertices=GEOMETRY;var lines=vertices.getBuffer(RenderLayer.getLines());float fogStart=RenderSystem.getShaderFogStart(),fogEnd=RenderSystem.getShaderFogEnd();RenderSystem.setShaderFogStart(384);RenderSystem.setShaderFogEnd(512);
            for(var v:active.values()){double t=age(v)+ctx.tickDelta();if(t>v.duration+60||eye.subtract(Vec3d.ofCenter(v.center)).horizontalLength()>v.radius+192)continue;float opacity=(float)Math.max(0,Math.min(1,Math.min((t-160)/40,(v.duration+60-t)/60)));Vec3d p=position(v,t);
                if(t<200){ring(m,lines,p,v.type==0?48:v.radius,1,.7F,.15F);continue;}
                if(v.type==0){boolean distant=eye.distanceTo(p)>180;StormGeometry.tornado(m,vertices.getBuffer(StormLayers.texture(Hardcore.id("textures/effects/tornado.png"))),lines,p,t,opacity,distant,v.width,Math.max(200,crown(v,t)-p.y));if(opacity>.1F)StormGeometry.debris(m,vertices,p,t,v.width,Math.max(200,crown(v,t)-p.y),distant,client.options.getParticles().getValue());}
                if(v.type==3)StormGeometry.clouds(m,vertices.getBuffer(StormLayers.texture(Hardcore.id("textures/effects/tornado.png"))),p,t,opacity,v.radius);

                if(v.type==1){double pulse=(t-200)%160;if(pulse<40)ring(m,lines,Vec3d.ofBottomCenter(v.center),v.radius*(pulse/40),1,.68F,.12F);else if(pulse<60){for(int i=0;i<8;i++){double a=i*Math.PI/4;WorldRenderer.drawBox(m,lines,v.center.getX()+Math.cos(a)*pulse*.6-.4,v.center.getY()+.1,v.center.getZ()+Math.sin(a)*pulse*.6-.4,v.center.getX()+Math.cos(a)*pulse*.6+.4,v.center.getY()+.2,v.center.getZ()+Math.sin(a)*pulse*.6+.4,.7F,.4F,.16F,1);}}}
                if(v.type==1)StormGeometry.quake(m,vertices.getBuffer(StormLayers.texture(Hardcore.id("textures/effects/tornado.png"))),lines,Vec3d.ofBottomCenter(v.center),(t-200)%160,opacity,v.radius);
                if(v.type>=3)for(var mark:v.marks){double cycle=(t-200)%(v.type==3?120:80);ring(m,lines,mark,v.type==3?2:4,1,.38F,.13F);if(v.type==4)StormGeometry.meteor(m,vertices.getBuffer(StormLayers.texture(Hardcore.id("textures/effects/meteor.png"))),lines,mark,cycle,opacity);else if(cycle>=40&&cycle<52)StormGeometry.lightning(m,lines,mark,55,v.id.getLeastSignificantBits()+(int)(t/120),opacity);}

            }
            if(client.world.getRegistryKey()==EventDirector.DIMENSION&&!EventPresentation.id.isEmpty()&&EventPresentation.type.equals("circuito"))for(int i=0;i<12;i++){Vec3d p=EventDirector.ringPosition(EventPresentation.center,i);verticalRing(m,lines,p,3.5,i==EventPresentation.checkpoint?1:.35F,i==EventPresentation.checkpoint?.75F:.9F,1);}
            vertices.draw();RenderSystem.setShaderFogStart(fogStart);RenderSystem.setShaderFogEnd(fogEnd);m.pop();
        });
        HudRenderCallback.EVENT.register((draw,delta)->{var client=MinecraftClient.getInstance();if(client.player==null||client.options.hudHidden)return;float dark=darkness();if(shaders&&dark>0)draw.fill(0,0,draw.getScaledWindowWidth(),draw.getScaledWindowHeight(),((int)(dark*100)<<24)|0x0d111c);float acid=acid();if(shaders&&acid>0)draw.fill(0,0,draw.getScaledWindowWidth(),draw.getScaledWindowHeight(),((int)(acid*80)<<24)|0xc3a72b);for(var v:active.values())if(client.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength()<v.radius){int t=(int)age(v);String name=Cataclysms.TYPES[v.type].toUpperCase();draw.drawCenteredTextWithShadow(client.textRenderer,t<200?name+" EN "+((200-t+19)/20)+" s":name+" · "+Math.max(0,(v.duration-t)/20)+" s",draw.getScaledWindowWidth()/2,client.world.getRegistryKey()==EventDirector.DIMENSION?58:18,0xffd367);break;}});
    }
    private static void tick(MinecraftClient c){if(c.world!=world){clear();world=c.world;}if(c.world==null||c.player==null)return;if(c.world.getTime()%20==0)try{var api=Class.forName("net.irisshaders.iris.api.v0.IrisApi");shaders=(Boolean)api.getMethod("isShaderPackInUse").invoke(api.getMethod("getInstance").invoke(null));}catch(ReflectiveOperationException absent){shaders=false;}active.values().removeIf(v->age(v)>v.duration+60||c.world.getTime()-v.received>60);for(var entry:new ArrayList<>(sounds.entrySet()))if(!active.containsKey(entry.getKey())||(age(active.get(entry.getKey()))<200)!=entry.getValue().warning){c.getSoundManager().stop(entry.getValue());sounds.remove(entry.getKey());}for(var v:active.values())if(!sounds.containsKey(v.id)){var sound=new StormSound(v);sounds.put(v.id,sound);c.getSoundManager().play(sound);}int amount=c.options.getParticles().getValue()==net.minecraft.client.option.ParticlesMode.MINIMAL?0:c.options.getParticles().getValue()==net.minecraft.client.option.ParticlesMode.DECREASED?2:6;
        for(var v:active.values()){double t=age(v);if((v.type==0||v.type==3)&&t>=200&&t<v.duration&&c.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength()<v.radius&&(int)t%70==0)c.world.playSound(c.player.getX(),c.player.getY()+3,c.player.getZ(),RegistriesSound.event(v.type==0?"disaster.wind_thunder":"disaster.thunder"),SoundCategory.WEATHER,.85F,.8F+(float)((t/70)%3)*.08F,false);if(t<200||t>v.duration||c.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength()>v.radius+16)continue;for(int i=0;i<(v.type==1?amount*3:amount);i++){double x=c.player.getX()+c.world.random.nextDouble()*32-16,z=c.player.getZ()+c.world.random.nextDouble()*32-16,y=c.player.getY()+10+c.world.random.nextDouble()*8;if(v.type==2&&c.world.getTopY(Heightmap.Type.MOTION_BLOCKING,MathHelper.floor(x),MathHelper.floor(z))<y){c.world.addParticle(Cataclysms.ACID_DROP,x,y,z,0,-.8,0);}else if(v.type==0)c.world.addParticle(ParticleTypes.CLOUD,x,y-8,z,.25,.13,.25);else if(v.type==1&&(t-200)%160>=40&&(t-200)%160<120)c.world.addParticle(ParticleTypes.POOF,x,c.world.getTopY(Heightmap.Type.MOTION_BLOCKING,MathHelper.floor(x),MathHelper.floor(z))+.2,z,0,.12,0);}}
    }
    public static float darkness(){var c=MinecraftClient.getInstance();if(c.player==null||c.world==null)return 0;float result=0;for(var v:active.values())if(v.type==0||v.type==3){double t=age(v),distance=c.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength();float area=(float)Math.max(0,Math.min(1,(v.radius+40-distance)/60));float fade=(float)Math.max(0,Math.min(1,Math.min((t-120)/80,(v.duration+60-t)/60)));result=Math.max(result,area*fade*(v.type==0?.62F:.52F));}return result;}
    public static float acid(){var c=MinecraftClient.getInstance();if(c.player==null||c.world==null)return 0;for(var v:active.values())if(v.type==2&&age(v)>=200&&age(v)<v.duration+60&&c.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength()<v.radius){boolean roof=c.world.getTopY(Heightmap.Type.MOTION_BLOCKING,c.player.getBlockX(),c.player.getBlockZ())>c.player.getY()+1.9;float fade=(float)Math.max(0,Math.min(1,Math.min((age(v)-200)/30,(v.duration+60-age(v))/60)));return (roof?.12F:.45F)*fade;}return 0;}
    public static float shake(float delta){if(!shake||RitualCinema.current()!=null)return 0;var c=MinecraftClient.getInstance();if(c.player==null)return 0;for(var v:active.values())if(v.type==1&&age(v)>=200&&age(v)<v.duration&&c.player.getPos().subtract(Vec3d.ofCenter(v.center)).horizontalLength()<v.radius){double t=age(v)+delta;double pulse=(t-200)%160;return pulse>=40&&pulse<120?(float)((Math.sin(t*2.1)*2.7+Math.sin(t*.83)*1.4)*(120-pulse)/80):pulse<40?(float)(Math.sin(t*1.8)*.22):0;}return 0;}
    private static void ring(MatrixStack m,VertexConsumer v,Vec3d p,double radius,float r,float g,float b){StormGeometry.ring(m,v,p,radius,r,g,b,1);}
    private static void verticalRing(MatrixStack m,VertexConsumer v,Vec3d p,double radius,float r,float g,float b){for(int i=0;i<48;i++){double a=i*Math.PI/24,next=(i+1)*Math.PI/24;StormGeometry.beam(m,v,p.add(Math.cos(a)*radius,Math.sin(a)*radius,0),p.add(Math.cos(next)*radius,Math.sin(next)*radius,0),.055,r,g,b,1);}}
    private static void quad(MatrixStack m,VertexConsumer v,Vec3d a,Vec3d b,Vec3d c,Vec3d d,float u,float u1,float y,float y1,float alpha,float r,float g,float blue){vertex(m,v,a,u,y,alpha,r,g,blue);vertex(m,v,b,u1,y,alpha,r,g,blue);vertex(m,v,c,u1,y1,alpha,r,g,blue);vertex(m,v,d,u,y1,alpha,r,g,blue);}
    private static void vertex(MatrixStack m,VertexConsumer v,Vec3d p,float u,float y,float a,float r,float g,float b){v.vertex(m.peek().getPositionMatrix(),(float)p.x,(float)p.y,(float)p.z).color(r,g,b,a).texture(u,y).overlay(OverlayTexture.DEFAULT_UV).light(15728880).normal(m.peek().getNormalMatrix(),0,1,0).next();}
    private static void cube(MatrixStack m,VertexConsumer v,Vec3d p,float s,float r,float g,float b,float a){Vec3d[] q={p.add(-s,-s,-s),p.add(s,-s,-s),p.add(s,s,-s),p.add(-s,s,-s),p.add(-s,-s,s),p.add(s,-s,s),p.add(s,s,s),p.add(-s,s,s)};for(int[] face:new int[][]{{0,3,2,1},{4,5,6,7},{0,4,7,3},{1,2,6,5},{3,7,6,2},{0,1,5,4}})quad(m,v,q[face[0]],q[face[1]],q[face[2]],q[face[3]],0,1,0,1,a,r,g,b);}
    private static final class RegistriesSound {static SoundEvent event(String name){return net.minecraft.registry.Registries.SOUND_EVENT.get(Hardcore.id(name));}}
}
