package net.tecnihardcore;

import com.google.gson.*;
import net.fabricmc.fabric.api.networking.v1.*;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import net.minecraft.text.Text;
import com.mojang.brigadier.arguments.*;
import java.util.*;
import static net.minecraft.server.command.CommandManager.*;

public final class CivicNetwork {
    public static final Identifier OPEN=Hardcore.id("civic_open_v1"),ACTION=Hardcore.id("civic_action_v1");
    private record Session(UUID nonce,UUID npc,String kind,String node,String tab,int page,int expires){}
    private static final Map<UUID,Session> sessions=new HashMap<>();
    static void init(){
        ServerPlayConnectionEvents.DISCONNECT.register((h,s)->sessions.remove(h.player.getUuid()));
        net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.SERVER_STOPPED.register(s->sessions.clear());
        ServerPlayNetworking.registerGlobalReceiver(ACTION,(s,p,h,b,r)->{UUID nonce=b.readUuid();String action=b.readString(24),id=b.readString(64),value=b.readString(4096);s.execute(()->{Session session=sessions.get(p.getUuid());if(session==null||!session.nonce.equals(nonce)||session.expires<s.getTicks()||!Social.ready(p))return;var entity=p.getServerWorld().getEntity(session.npc);if(!(entity instanceof CivicNpcEntity npc)||p.squaredDistanceTo(npc)>64)return;sessions.remove(p.getUuid());try{
            if(session.kind.equals("npc")&&action.equals("choice")){var def=CivicNpcs.definitions.get(npc.key());if(def==null)return;var node=def.dialogue.get(session.node);int index=Integer.parseInt(id);if(node==null||index<0||index>=node.options.size())return;var option=node.options.get(index);if(option.action.equals("market")){market(p,npc,"all",0);return;}if(option.action.equals("close"))return;if(option.action.startsWith("quest_start:"))CivicQuests.start(p,option.action.substring(12));if(option.action.startsWith("quest_claim:"))CivicQuests.claim(p,option.action.substring(12));dialogue(p,npc,option.next.isEmpty()?session.node:option.next);}
            else if(session.kind.equals("market")){if(!Market.available(p))return;switch(action){case "tab"->market(p,npc,Set.of("all","mine","mail").contains(id)?id:"all",0);case "page"->market(p,npc,session.tab,Math.max(0,Math.min(10000,session.page+Integer.parseInt(id))));case "publish"->{Market.sell(p,Long.parseLong(value));market(p,npc,"mine",0);}case "buy"->{Market.buy(p,id);market(p,npc,session.tab,session.page);}case "cancel"->{Market.cancel(p,id);market(p,npc,"mine",session.page);}case "withdraw"->{Market.withdraw(p,id);market(p,npc,"mail",session.page);}default->market(p,npc,session.tab,session.page);}}
            else if(session.kind.equals("editor")&&p.hasPermissionLevel(4)&&action.equals("edit")){var old=CivicNpcs.definitions.get(npc.key());if(old==null)return;var updated=SocialStore.JSON.fromJson(SocialStore.JSON.toJson(old),CivicNpcs.Definition.class);var request=JsonParser.parseString(value).getAsJsonObject();String nodeId=request.get("node").getAsString();if(!nodeId.matches("[a-z0-9_-]{1,32}"))return;updated.name=request.get("name").getAsString();var node=updated.dialogue.computeIfAbsent(nodeId,k->new CivicNpcs.Node());node.text=request.get("text").getAsString();String label=request.get("label").getAsString();if(!label.isBlank())node.options.add(new CivicNpcs.Option(label,request.get("next").getAsString(),request.get("action").getAsString()));int remove=request.get("remove").getAsInt();if(remove>=0&&remove<node.options.size())node.options.remove(remove);CivicNpcs.definitions.put(npc.key(),updated);try{CivicNpcs.validate();CivicNpcs.save();}catch(Exception error){CivicNpcs.definitions.put(npc.key(),old);throw error;}CivicNpcs.ensure();editor(p,npc,nodeId);}
        }catch(Exception error){Social.say(p,"No se pudo aplicar: "+error.getMessage());Hardcore.LOG.warn("Civic request rejected {}: {}",p.getUuidAsString(),error.getClass().getSimpleName());}});});
        CommandRegistrationCallback.EVENT.register((d,r,e)->{
            d.register(literal("mercado").requires(s->s.getEntity() instanceof ServerPlayerEntity).executes(c->{var p=c.getSource().getPlayerOrThrow();if(!Market.available(p))return 0;var npc=p.getServerWorld().getEntitiesByClass(CivicNpcEntity.class,p.getBoundingBox().expand(6),n->{var def=CivicNpcs.definitions.get(n.key());return def!=null&&def.role.equals("merchant");}).get(0);market(p,npc,"all",0);return 1;}).then(literal("vender").then(argument("precio",LongArgumentType.longArg(1,1000000)).executes(c->{Market.sell(c.getSource().getPlayerOrThrow(),LongArgumentType.getLong(c,"precio"));return 1;}))));
            d.register(literal("cristales").requires(s->s.getEntity() instanceof ServerPlayerEntity).executes(c->{var p=c.getSource().getPlayerOrThrow();if(Social.ready(p))Social.say(p,"Saldo: "+Market.balance(p.getUuidAsString())+" Cristales Tecni.");return 1;}));
            d.register(literal("tecni").then(literal("moneda").requires(s->s.hasPermissionLevel(4)).then(literal("dar").then(argument("jugador",StringArgumentType.word()).then(argument("cantidad",LongArgumentType.longArg(1,1000000)).executes(c->{var p=c.getSource().getServer().getPlayerManager().getPlayer(StringArgumentType.getString(c,"jugador"));if(p==null)return 0;var b=Social.store.copy();b.wallets.put(p.getUuidAsString(),SocialRules.transfer(Market.balance(p.getUuidAsString()),LongArgumentType.getLong(c,"cantidad")));Social.store.commit(b,"admin grant by "+c.getSource().getName()+" to "+p.getUuidAsString());Social.say(p,"Recibiste Cristales Tecni. Saldo: "+Market.balance(p.getUuidAsString()));return 1;}))))));
        });
    }
    private static JsonObject base(String kind,String title,String body){var json=new JsonObject();json.addProperty("kind",kind);json.addProperty("title",title);json.addProperty("body",body);json.add("entries",new JsonArray());return json;}
    private static void send(ServerPlayerEntity p,CivicNpcEntity npc,String kind,String node,String tab,int page,JsonObject json){if(!ClientSafe.canSend(p))return;UUID nonce=UUID.randomUUID();sessions.put(p.getUuid(),new Session(nonce,npc.getUuid(),kind,node,tab,page,p.getServer().getTicks()+6000));json.addProperty("nonce",nonce.toString());var b=PacketByteBufs.create();b.writeString(json.toString(),32767);ServerPlayNetworking.send(p,OPEN,b);}
    static void dialogue(ServerPlayerEntity p,CivicNpcEntity npc,String node){if(!Social.ready(p)||p.squaredDistanceTo(npc)>64)return;var def=CivicNpcs.definitions.get(npc.key());if(def==null)return;var n=def.dialogue.get(node);if(n==null){Social.say(p,"Ese diálogo aún no está definido.");return;}var json=base("npc",def.name,n.text);for(int i=0;i<n.options.size();i++){var o=n.options.get(i);var e=new JsonObject();e.addProperty("id",Integer.toString(i));e.addProperty("label",o.label);e.addProperty("action","choice");json.getAsJsonArray("entries").add(e);}send(p,npc,"npc",node,"",0,json);}
    static void editor(ServerPlayerEntity p,CivicNpcEntity npc,String node){if(!p.hasPermissionLevel(4)||p.squaredDistanceTo(npc)>64){Social.say(p,"Acércate al NPC (8 bloques) para editarlo.");return;}var def=CivicNpcs.definitions.get(npc.key());if(def==null)return;var n=def.dialogue.getOrDefault(node,new CivicNpcs.Node());var json=base("editor","Editar · "+def.name,"Nodo "+node+" · "+n.options.size()+" opciones. Borrar usa el número desde 1.");json.addProperty("name",def.name);json.addProperty("node",node);json.addProperty("text",n.text);for(int i=0;i<n.options.size();i++){var o=n.options.get(i);var e=new JsonObject();e.addProperty("label",(i+1)+": "+o.label+" → "+o.next+" "+o.action);e.addProperty("id","noop");e.addProperty("action","noop");json.getAsJsonArray("entries").add(e);}send(p,npc,"editor",node,"",0,json);}
    static void market(ServerPlayerEntity p,CivicNpcEntity npc,String tab,int page){if(!Market.available(p))return;var json=base("market","Mercado · Cristales Tecni","Saldo: "+Market.balance(p.getUuidAsString())+" · Publicar entrega el lote completo de tu mano principal.");json.addProperty("tab",tab);var list=new ArrayList<JsonObject>();if(tab.equals("mail")){for(var parcel:Social.store.data.parcels.values())if(parcel.owner.equals(p.getUuidAsString())){var e=new JsonObject();e.addProperty("id",parcel.id);e.addProperty("label",parcel.reason);e.addProperty("action","withdraw");e.addProperty("item",parcel.item);list.add(e);}}else for(var offer:Social.store.data.offers.values())if(offer.state.equals("open")&&(!tab.equals("mine")||offer.seller.equals(p.getUuidAsString()))){var e=new JsonObject();e.addProperty("id",offer.id);e.addProperty("label",offer.sellerName+" · "+offer.price+" CT");e.addProperty("action",offer.seller.equals(p.getUuidAsString())?"cancel":"buy");e.addProperty("item",offer.item);list.add(e);}page=Math.max(0,Math.min(page,Math.max(0,(list.size()-1)/5)));for(int i=page*5;i<Math.min(list.size(),page*5+5);i++)json.getAsJsonArray("entries").add(list.get(i));json.addProperty("page",page+1);json.addProperty("pages",Math.max(1,(list.size()+4)/5));send(p,npc,"market","",tab,page,json);}
    private static final class ClientSafe {static boolean canSend(ServerPlayerEntity p){if(ServerPlayNetworking.canSend(p,OPEN))return true;Social.say(p,"Actualiza el launcher para usar NPCs y mercado.");return false;}}
}
