package net.tecnihardcore;

import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.registry.*;
import net.minecraft.util.*;
import net.minecraft.util.math.*;
import net.minecraft.world.*;
import com.mojang.brigadier.arguments.StringArgumentType;
import java.nio.file.*;
import java.util.*;
import static net.minecraft.server.command.CommandManager.*;

public final class CivicNpcs {
    public static final class Option {public String label="",next="",action="";Option(){}Option(String label,String next,String action){this.label=label;this.next=next;this.action=action;}}
    public static final class Node {public String text="";public List<Option> options=new ArrayList<>();Node(){}Node(String text,Option... options){this.text=text;this.options.addAll(Arrays.asList(options));}}
    public static final class Definition {public String name="",dimension="minecraft:overworld",role="guide",skinHash="",fallback="steve";public boolean slim;public double x,y,z;public Map<String,Node> dialogue=new LinkedHashMap<>();}
    static Map<String,Definition> definitions=new LinkedHashMap<>();private static Path file;private static MinecraftServer server;
    static void init(){CivicNpcEntity.init();CivicNetwork.init();NpcSkins.init();
        ServerLifecycleEvents.SERVER_STARTED.register(s->{server=s;file=s.getRunDirectory().toPath().resolve("config/tecnihardcore/npcs.json");load();});
        ServerLifecycleEvents.SERVER_STOPPED.register(s->{server=null;definitions.clear();NpcSkins.clear();});
        ServerTickEvents.END_SERVER_TICK.register(s->{if(s.getTicks()%100==0)ensure();if(s.getTicks()%20==0)for(var p:s.getPlayerManager().getPlayerList())CivicQuests.tick(p);});
        ServerEntityEvents.ENTITY_LOAD.register((entity,w)->{if(entity instanceof CivicNpcEntity npc){var def=definitions.get(npc.key());if(def==null)npc.discard();else npc.configure(npc.key(),def);}});
        CommandRegistrationCallback.EVENT.register((d,r,e)->{
            var root=literal("npc").requires(s->s.hasPermissionLevel(4));root.then(literal("listar").executes(c->{definitions.forEach((id,n)->c.getSource().sendFeedback(()->net.minecraft.text.Text.literal(id+" · "+n.name+" · "+n.dimension+" "+(int)n.x+" "+(int)n.y+" "+(int)n.z),false));return definitions.size();}));
            root.then(literal("crear").then(argument("id",StringArgumentType.word()).then(argument("nombre",StringArgumentType.greedyString()).executes(c->{var p=c.getSource().getPlayerOrThrow();String id=StringArgumentType.getString(c,"id");if(!id.matches("[a-z0-9_-]{1,32}")||definitions.containsKey(id)||definitions.size()>=64)return 0;var n=new Definition();n.name=StringArgumentType.getString(c,"nombre");n.dimension=p.getWorld().getRegistryKey().getValue().toString();n.x=p.getX();n.y=p.getY();n.z=p.getZ();n.dialogue.put("inicio",new Node("Hola, viajero.",new Option("Hasta luego","","close")));definitions.put(id,n);try{save();}catch(Exception error){definitions.remove(id);throw error;}ensure();return 1;}))));
            root.then(literal("editar").then(argument("id",StringArgumentType.word()).executes(c->edit(c.getSource().getPlayerOrThrow(),StringArgumentType.getString(c,"id"),"inicio")).then(argument("nodo",StringArgumentType.word()).executes(c->edit(c.getSource().getPlayerOrThrow(),StringArgumentType.getString(c,"id"),StringArgumentType.getString(c,"nodo"))))));
            root.then(literal("mover").then(argument("id",StringArgumentType.word()).executes(c->{var p=c.getSource().getPlayerOrThrow();String id=StringArgumentType.getString(c,"id");var n=definitions.get(id);if(n==null)return 0;removeEntities(id);n.dimension=p.getWorld().getRegistryKey().getValue().toString();n.x=p.getX();n.y=p.getY();n.z=p.getZ();save();ensure();return 1;})));
            root.then(literal("eliminar").then(argument("id",StringArgumentType.word()).executes(c->{String id=StringArgumentType.getString(c,"id");definitions.remove(id);removeEntities(id);save();return 1;})));
            root.then(literal("skin").then(argument("id",StringArgumentType.word()).then(argument("url",StringArgumentType.greedyString()).executes(c->{var p=c.getSource().getPlayerOrThrow();NpcSkins.fetch(p,StringArgumentType.getString(c,"id"),StringArgumentType.getString(c,"url"));return 1;}))));
            root.then(literal("recargar").executes(c->{load();ensure();return 1;}));d.register(literal("tecni").then(root));
        });
    }
    static int edit(ServerPlayerEntity p,String id,String node){var entity=find(id);if(entity==null||!node.matches("[a-z0-9_-]{1,32}")){Social.say(p,"NPC no cargado o nodo inválido.");return 0;}CivicNetwork.editor(p,entity,node);return 1;}
    static boolean nearMerchant(ServerPlayerEntity p){return p.getServerWorld().getEntitiesByClass(CivicNpcEntity.class,p.getBoundingBox().expand(6),n->{var d=definitions.get(n.key());return d!=null&&d.role.equals("merchant")&&n.squaredDistanceTo(p)<=36;}).size()>0;}
    static CivicNpcEntity find(String id){if(server==null)return null;for(var w:server.getWorlds())for(var entity:w.iterateEntities())if(entity instanceof CivicNpcEntity n&&n.key().equals(id))return n;return null;}
    private static void removeEntities(String id){if(server!=null)for(var w:server.getWorlds())for(var entity:w.iterateEntities())if(entity instanceof CivicNpcEntity n&&n.key().equals(id))n.discard();}
    static void ensure(){if(server==null)return;for(var entry:definitions.entrySet()){var n=entry.getValue();var w=server.getWorld(RegistryKey.of(RegistryKeys.WORLD,new Identifier(n.dimension)));if(w==null)continue;BlockPos pos=BlockPos.ofFloored(n.x,n.y,n.z);if(!w.isChunkLoaded(pos))continue;if(!w.getBlockState(pos).getCollisionShape(w,pos).isEmpty()||!w.getBlockState(pos.up()).getCollisionShape(w,pos.up()).isEmpty())continue;var existing=find(entry.getKey());if(existing!=null){if(existing.getWorld()!=w){existing.discard();existing=null;}else{existing.configure(entry.getKey(),n);if(existing.squaredDistanceTo(n.x,n.y,n.z)>.01)existing.refreshPositionAndAngles(n.x,n.y,n.z,existing.getYaw(),existing.getPitch());continue;}}var entity=new CivicNpcEntity(CivicNpcEntity.TYPE,w);entity.configure(entry.getKey(),n);entity.refreshPositionAndAngles(n.x,n.y,n.z,180,0);w.spawnEntity(entity);}}
    static void validate(){if(definitions.size()>64)throw new IllegalArgumentException("Too many NPCs");for(var pair:definitions.entrySet()){var d=pair.getValue();if(!pair.getKey().matches("[a-z0-9_-]{1,32}")||d==null||d.name.length()>64||!Double.isFinite(d.x)||!Double.isFinite(d.y)||!Double.isFinite(d.z)||Math.abs(d.x)>30000000||Math.abs(d.z)>30000000||d.dialogue.size()>64||!d.dialogue.containsKey("inicio")||!Set.of("guide","merchant").contains(d.role)||!d.skinHash.matches("([a-f0-9]{64})?"))throw new IllegalArgumentException("Invalid NPC");new Identifier(d.dimension);for(var n:d.dialogue.values()){if(n.text.length()>2048||n.options.size()>8)throw new IllegalArgumentException("Invalid dialogue");for(var o:n.options)if(o.label.length()>80||!o.next.matches("([a-z0-9_-]{1,32})?")||!o.action.matches("(close|market|quest_start:(sendero|madera|hierro)|quest_claim:(sendero|madera|hierro))?"))throw new IllegalArgumentException("Invalid option");}}}
    static void save(){try{validate();Files.createDirectories(file.getParent());Path tmp=file.resolveSibling("npcs.json.tmp");Files.writeString(tmp,SocialStore.JSON.toJson(definitions),java.nio.charset.StandardCharsets.UTF_8);try(var c=java.nio.channels.FileChannel.open(tmp,StandardOpenOption.WRITE)){c.force(true);}if(Files.exists(file))Files.copy(file,file.resolveSibling("npcs.json.previous"),StandardCopyOption.REPLACE_EXISTING);Files.move(tmp,file,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){throw new IllegalStateException("Cannot save NPC definitions",e);}}
    private static void load(){try{if(Files.exists(file)){var type=new com.google.gson.reflect.TypeToken<LinkedHashMap<String,Definition>>(){}.getType();definitions=SocialStore.JSON.fromJson(Files.readString(file,java.nio.charset.StandardCharsets.UTF_8),type);validate();}else{defaults();save();}}catch(Exception e){throw new IllegalStateException("Invalid NPC definitions; refusing to overwrite",e);}}
    private static void defaults(){
        var guide=at("Inés · Exploradora",-14,-12,"alex");guide.slim=true;guide.dialogue.put("inicio",new Node("Bienvenido a TecniHardcore. Tenés tres vidas: prepará un refugio antes de salir a explorar. Puedo ayudarte con tus primeros pasos.",new Option("Aceptar: Más allá de la plaza","","quest_start:sendero"),new Option("Cobrar exploración: 15 Cristales Tecni","","quest_claim:sendero"),new Option("¿Cómo funcionan las vidas?","vidas",""),new Option("¿Cómo creo un equipo?","equipos","")));guide.dialogue.put("vidas",new Node("Morir consume una vida. Al agotarlas quedás en espectador. Otro superviviente puede revivirte en el santuario ofreciendo un Corazón Sagrado; volverás con una vida. Los tótems evitan la muerte, pero tienen enfriamiento.",new Option("Volver","inicio","")));guide.dialogue.put("equipos",new Node("Usa /team crear Nombre y /team invitar Jugador. /team o /chat cambia entre chat general y privado. No podés dañar a tus compañeros. Una expulsión crea una tregua de dos horas de conexión del expulsado.",new Option("Volver","inicio","")));definitions.put("ines",guide);
        var smith=at("Bruno · Intendente",14,-12,"efe");smith.dialogue.put("inicio",new Node("Un refugio y herramientas valen más que una pelea improvisada. Traeme suministros: estos contratos iniciales se pagan una sola vez y consumen lo que entregás.",new Option("Aceptar: entregar 16 troncos","","quest_start:madera"),new Option("Entregar troncos: 25 Cristales Tecni","","quest_claim:madera"),new Option("Aceptar: entregar 4 hierros en bruto","","quest_start:hierro"),new Option("Entregar hierro: 40 Cristales Tecni","","quest_claim:hierro")));definitions.put("bruno",smith);
        var merchant=at("Selma · Mercader",14,12,"zuri");merchant.role="merchant";merchant.dialogue.put("inicio",new Node("Acá comerciás con otros supervivientes usando Cristales Tecni. Cada anuncio guarda el lote completo en custodia; las compras van a tu buzón. Vos elegís el precio.",new Option("Ver mercado","","market"),new Option("Cómo ganar Cristales Tecni","moneda","")));merchant.dialogue.put("moneda",new Node("Inés y Bruno ofrecen misiones iniciales. Luego podés ganar cristales vendiendo a otros jugadores. El saldo lo guarda el servidor y el vendedor recibe el pago aunque esté desconectado.",new Option("Volver","inicio","")));definitions.put("selma",merchant);
    }
    private static Definition at(String name,int x,int z,String skin){var world=server.getOverworld();boolean plaza=SpawnProtection.active(world);var spawn=world.getSpawnPos();if(!plaza){x+=spawn.getX();z+=spawn.getZ();}var n=new Definition();n.name=name;n.x=x+.5;n.z=z+.5;n.y=plaza?96:world.isChunkLoaded(new BlockPos(x,spawn.getY(),z))?world.getTopY(Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,x,z):spawn.getY();n.fallback=skin;return n;}
}
