package net.tecnihardcore;

import net.fabricmc.fabric.api.object.builder.v1.entity.*;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.networking.v1.*;
import net.minecraft.entity.*;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.damage.DamageSource;
import net.minecraft.entity.data.*;
import net.minecraft.entity.mob.PathAwareEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.*;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.registry.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.Text;
import net.minecraft.util.*;
import net.minecraft.util.math.*;
import net.minecraft.world.World;
import software.bernie.geckolib.animatable.GeoEntity;
import software.bernie.geckolib.core.animatable.instance.AnimatableInstanceCache;
import software.bernie.geckolib.core.animation.*;
import software.bernie.geckolib.util.GeckoLibUtil;
import static net.minecraft.server.command.CommandManager.*;

public final class CrystalMount extends PathAwareEntity implements GeoEntity {
    public static final Identifier INPUT=Hardcore.id("mount_input_v1");
    public static final EntityType<CrystalMount> TYPE=Registry.register(Registries.ENTITY_TYPE,Hardcore.id("bestia_cristal"),FabricEntityTypeBuilder.create(SpawnGroup.CREATURE,CrystalMount::new).dimensions(EntityDimensions.fixed(2.1F,1.8F)).trackRangeBlocks(96).trackedUpdateRate(1).build());
    public static final Item TOKEN=Registry.register(Registries.ITEM,Hardcore.id("invocacion_cristal"),new Item(new Item.Settings().maxCount(1).fireproof()){
        @Override public TypedActionResult<ItemStack> use(World w,PlayerEntity player,Hand hand){var stack=player.getStackInHand(hand);if(w.isClient)return TypedActionResult.success(stack);if(!(player instanceof ServerPlayerEntity p)||!AuthBootstrap.authenticated(p)||p.isSpectator()||p.isCreative()||Hardcore.soul(p).lives<=0||EventDirector.participant(p))return TypedActionResult.fail(stack);
            String id=stack.hasNbt()?stack.getNbt().getString("CrystalMount"):"";var m=Expansion.store.data.mounts.get(id);if(m==null||m.state.equals("muerta")){p.sendMessage(Text.literal("Esta montura ya no existe."),true);return TypedActionResult.fail(stack);}if(!m.state.equals("guardada")){p.sendMessage(Text.literal("La montura ya está activa."),true);return TypedActionResult.fail(stack);}for(var v:Expansion.store.data.mounts.values())if(v.state.equals("activa")&&v.holder.equals(p.getUuidAsString())){p.sendMessage(Text.literal("Ya tienes una montura activa."),true);return TypedActionResult.fail(stack);}
            var entity=new CrystalMount(TYPE,w);entity.mountId=id;entity.dataTracker.set(TIER,m.tier);entity.getAttributeInstance(EntityAttributes.GENERIC_MAX_HEALTH).setBaseValue(ExpansionRules.HEALTH[m.tier-1]);entity.setHealth(m.health);entity.refreshPositionAndAngles(p.getX()+Math.cos(Math.toRadians(p.getYaw()))*3,p.getY()+.2,p.getZ()+Math.sin(Math.toRadians(p.getYaw()))*3,p.getYaw(),0);
            if(!w.isSpaceEmpty(entity)||!w.isChunkLoaded(entity.getBlockPos())||!w.getWorldBorder().contains(entity.getBoundingBox())){p.sendMessage(Text.literal("Busca espacio libre para invocar la montura."),true);return TypedActionResult.fail(stack);}m.state="activa";m.holder=p.getUuidAsString();m.entity=entity.getUuidAsString();m.dimension=w.getRegistryKey().getValue().toString();m.x=entity.getX();m.y=entity.getY();m.z=entity.getZ();Expansion.store.save();if(!w.spawnEntity(entity)){m.state="guardada";m.entity="";Expansion.store.save();return TypedActionResult.fail(stack);}return TypedActionResult.success(stack);
        }
        @Override public void appendTooltip(ItemStack s,World w,java.util.List<Text> lines,net.minecraft.client.item.TooltipContext c){lines.add(Text.literal("Invoca con clic derecho; monta la bestia para volar."));lines.add(Text.literal("Amatista: cura. Agachado + clic: guarda en tierra."));lines.add(Text.literal("Si muere se pierde para siempre. Sin receta."));if(s.hasNbt())lines.add(Text.literal("Estado: "+s.getNbt().getString("CrystalState")+" · Salud: "+(int)s.getNbt().getFloat("CrystalHealth")));}
    });
    private static final TrackedData<Integer> TIER=DataTracker.registerData(CrystalMount.class,TrackedDataHandlerRegistry.INTEGER),STATE=DataTracker.registerData(CrystalMount.class,TrackedDataHandlerRegistry.INTEGER);
    private final AnimatableInstanceCache cache=GeckoLibUtil.createInstanceCache(this);
    String mountId="";public boolean landing;private float forward,side,vertical;private boolean boost;private long inputAt;private int animationDamage;private Vec3d landingTarget;
    public CrystalMount(EntityType<? extends PathAwareEntity> t,World w){super(t,w);setPersistent();setStepHeight(1);}
    public int tier(){return ExpansionRules.tier(dataTracker.get(TIER));}public int state(){return dataTracker.get(STATE);}
    public String holder(){var m=record();return m==null?"":m.holder;}
    private ExpansionStore.Mount record(){return Expansion.store==null?null:Expansion.store.data.mounts.get(mountId);}
    public String registryId(){return mountId;}
    public static void retireTemporary(ServerPlayerEntity p){if(Expansion.store==null)return;var entities=new java.util.ArrayList<Entity>();boolean changed=false;for(var m:Expansion.store.data.mounts.values())if(m.temporary&&m.state.equals("activa")&&m.holder.equals(p.getUuidAsString())){for(var w:p.getServer().getWorlds()){var entity=w.getEntity(java.util.UUID.fromString(m.entity));if(entity!=null)entities.add(entity);}m.state="muerta";m.entity="";m.health=0;changed=true;}if(changed){Expansion.store.save();for(var entity:entities)entity.discard();}}
    private boolean grounded(){return isOnGround()||Math.abs(getVelocity().y)<.2&&getWorld().getBlockCollisions(this,getBoundingBox().offset(0,-.05,0)).iterator().hasNext();}
    public void rememberReturn(){var m=record();if(m==null||m.temporary||landingTarget==null)return;m.returnPending=true;m.returnX=landingTarget.x;m.returnY=landingTarget.y;m.returnZ=landingTarget.z;Expansion.store.save();}
    public static ItemStack token(String id){var s=new ItemStack(TOKEN);s.getOrCreateNbt().putString("CrystalMount",id);var m=Expansion.store.data.mounts.get(id);if(m!=null){s.getOrCreateNbt().putInt("CrystalTier",m.tier);s.getOrCreateNbt().putFloat("CrystalHealth",m.health);s.getOrCreateNbt().putString("CrystalState",m.state);s.setCustomName(Text.literal(ExpansionRules.MOUNTS[m.tier-1]+" · Nivel "+m.tier).formatted(new net.minecraft.util.Formatting[]{net.minecraft.util.Formatting.WHITE,net.minecraft.util.Formatting.GREEN,net.minecraft.util.Formatting.AQUA,net.minecraft.util.Formatting.LIGHT_PURPLE,net.minecraft.util.Formatting.GOLD}[m.tier-1]));}return s;}
    public static void eventMount(ServerPlayerEntity p,String run){String id=java.util.UUID.randomUUID().toString();var m=new ExpansionStore.Mount();m.tier=3;m.health=55;m.temporary=true;m.state="activa";m.holder=p.getUuidAsString();var e=new CrystalMount(TYPE,p.getWorld());e.mountId=id;e.dataTracker.set(TIER,3);e.getAttributeInstance(EntityAttributes.GENERIC_MAX_HEALTH).setBaseValue(55);e.setHealth(55);e.refreshPositionAndAngles(p.getX(),p.getY()+3,p.getZ(),0,0);e.addCommandTag("TecniEvent:"+run);m.entity=e.getUuidAsString();m.dimension=p.getWorld().getRegistryKey().getValue().toString();m.x=e.getX();m.y=e.getY();m.z=e.getZ();Expansion.store.data.mounts.put(id,m);Expansion.store.save();p.getServerWorld().spawnEntity(e);p.startRiding(e);}
    public static void init(){
        FabricDefaultAttributeRegistry.register(TYPE,PathAwareEntity.createMobAttributes().add(EntityAttributes.GENERIC_MAX_HEALTH,30).add(EntityAttributes.GENERIC_MOVEMENT_SPEED,.3).add(EntityAttributes.GENERIC_FOLLOW_RANGE,16));
        net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.END_SERVER_TICK.register(s->{if(s.getTicks()%20!=0||Expansion.store==null)return;for(var p:s.getPlayerManager().getPlayerList())for(int slot=0;slot<p.getInventory().size();slot++){var stack=p.getInventory().getStack(slot);if(!stack.isOf(TOKEN)||!stack.hasNbt())continue;var n=stack.getNbt();var m=Expansion.store.data.mounts.get(n.getString("CrystalMount"));if(m!=null){n.putFloat("CrystalHealth",m.health);n.putString("CrystalState",m.state);}}});
        ServerPlayNetworking.registerGlobalReceiver(INPUT,(s,p,h,b,r)->{int entity=b.readVarInt();float f=b.readFloat(),side=b.readFloat(),vertical=b.readFloat();boolean boost=b.readBoolean();if(!Float.isFinite(f)||!Float.isFinite(side)||!Float.isFinite(vertical))return;s.execute(()->{if(p.getVehicle() instanceof CrystalMount m&&m.getId()==entity&&AuthBootstrap.authenticated(p)&&p.getUuidAsString().equals(m.holder())&&p.isAlive()&&!p.isSpectator()){m.forward=MathHelper.clamp(f,-1,1);m.side=MathHelper.clamp(side,-1,1);m.vertical=MathHelper.clamp(vertical,-1,1);m.boost=boost;m.inputAt=s.getTicks();}});});
        CommandRegistrationCallback.EVENT.register((d,a,e)->d.register(literal("tecni").then(literal("montura").requires(s->s.hasPermissionLevel(4)).then(literal("dar").then(argument("jugador",net.minecraft.command.argument.EntityArgumentType.player()).then(argument("nivel",com.mojang.brigadier.arguments.IntegerArgumentType.integer(1,5)).executes(c->{var p=net.minecraft.command.argument.EntityArgumentType.getPlayer(c,"jugador");int n=com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"nivel");String id=java.util.UUID.randomUUID().toString();var m=new ExpansionStore.Mount();m.tier=n;m.health=ExpansionRules.HEALTH[n-1];Expansion.store.data.mounts.put(id,m);Expansion.store.save();p.giveItemStack(token(id));Hardcore.LOG.warn("ADMIN {} granted mount {} tier {} to {}",c.getSource().getName(),id,n,p.getName().getString());return 1;})))))));
    }
    @Override protected void initDataTracker(){super.initDataTracker();dataTracker.startTracking(TIER,1);dataTracker.startTracking(STATE,0);}
    @Override public ActionResult interactMob(PlayerEntity player,Hand hand){if(getWorld().isClient)return ActionResult.SUCCESS;if(!(player instanceof ServerPlayerEntity p)||!AuthBootstrap.authenticated(p))return ActionResult.FAIL;var m=record();if(m==null||!p.getUuidAsString().equals(m.holder))return ActionResult.FAIL;var stack=p.getStackInHand(hand);long now=System.currentTimeMillis();
        if(stack.isOf(Items.AMETHYST_SHARD)&&now-m.damageAt>=15000&&now-m.healAt>=5000&&getHealth()<getMaxHealth()){heal(4);stack.decrement(1);m.health=getHealth();m.healAt=now;Expansion.store.save();return ActionResult.SUCCESS;}
        if(p.isSneaking()){if(grounded()&&!hasPassengers()&&now-m.damageAt>=15000){pack();return ActionResult.SUCCESS;}p.sendMessage(Text.literal("Aterriza, desmonta y espera 15 s sin daño para guardarla."),true);return ActionResult.FAIL;}
        if(!hasPassengers()&&!p.isSpectator()&&Hardcore.soul(p).lives>0)p.startRiding(this);return ActionResult.SUCCESS;
    }
    @Override public void travel(Vec3d input){if(getWorld().isClient){setNoGravity(state()>0);return;}var m=record();if(m==null)return;long ticks=getServer().getTicks(),now=System.currentTimeMillis();boolean riding=getFirstPassenger() instanceof ServerPlayerEntity p&&p.getUuidAsString().equals(m.holder)&&AuthBootstrap.authenticated(p);setNoGravity(riding||landing);if(riding){var p=(ServerPlayerEntity)getFirstPassenger();setYaw(p.getYaw());bodyYaw=getYaw();setPitch(p.getPitch()*.25F);if(ticks-inputAt>10){forward=side=vertical=0;boost=false;}if(boost&&now-m.boostAt>=24000){m.boostAt=now;Expansion.store.save();}boolean boosted=m.boostAt>0&&now-m.boostAt<4000;double speed=(boosted?ExpansionRules.BOOST[tier()-1]:ExpansionRules.SPEED[tier()-1])/20.0;Vec3d direction=new Vec3d(side,vertical*.7,forward);if(direction.lengthSquared()>1)direction=direction.normalize();direction=direction.rotateY((float)-Math.toRadians(getYaw()));Vec3d velocity=direction.multiply(speed);BlockPos ahead=BlockPos.ofFloored(getPos().add(velocity.multiply(8)));Box next=getBoundingBox().offset(velocity);if(!getWorld().isChunkLoaded(ahead)||!loadedBox(next)||!getWorld().getWorldBorder().contains(next))velocity=Vec3d.ZERO;setVelocity(p.hasStatusEffect(BossRoots.ROOT)?Vec3d.ZERO:getVelocity().lerp(velocity,.3));move(MovementType.SELF,getVelocity());dataTracker.set(STATE,isOnGround()&&vertical<=0?4:boosted?2:1);fallDistance=0;
        }else if(landing){dataTracker.set(STATE,4);if(landingTarget==null)requestLanding();Vec3d direction=landingTarget==null?new Vec3d(0,-.12,0):landingTarget.subtract(getPos());if(direction.lengthSquared()>.03)direction=direction.normalize().multiply(.15);else direction=new Vec3d(0,-.08,0);setVelocity(direction);fallDistance=0;move(MovementType.SELF,getVelocity());fallDistance=0;if(isOnGround()&&!hasPassengers()&&now-m.damageAt>=15000)pack();}else{dataTracker.set(STATE,0);setNoGravity(false);super.travel(input);}
    }
    @Override public void tick(){super.tick();if(getWorld().isClient||isDead())return;var m=record();if(m==null||!m.state.equals("activa")||!getUuidAsString().equals(m.entity)){discard();return;}if(!hasPassengers()&&!m.holder.isEmpty()&&getServer().getPlayerManager().getPlayer(java.util.UUID.fromString(m.holder))==null&&!landing)requestLanding();if(animationDamage>0){dataTracker.set(STATE,3);animationDamage--;}if(age%100==0){m.health=getHealth();m.x=getX();m.y=getY();m.z=getZ();Expansion.store.save();}}
    private boolean loadedBox(Box box){for(double x:new double[]{box.minX,box.maxX})for(double z:new double[]{box.minZ,box.maxZ})if(!getWorld().isChunkLoaded(BlockPos.ofFloored(x,box.minY,z)))return false;return true;}
    public void requestLanding(){landing=true;landingTarget=null;double best=Double.MAX_VALUE;for(int dx=-16;dx<=16;dx+=4)for(int dz=-16;dz<=16;dz+=4){BlockPos sample=getBlockPos().add(dx,0,dz);if(!getWorld().isChunkLoaded(sample))continue;BlockPos foot=getWorld().getTopPosition(net.minecraft.world.Heightmap.Type.MOTION_BLOCKING,sample);if(foot.getY()>getY()+2||foot.getY()<getWorld().getBottomY()+1||!getWorld().getBlockState(foot.down()).isSolidBlock(getWorld(),foot.down())||!getWorld().getFluidState(foot.down()).isEmpty()||!getWorld().getFluidState(foot).isEmpty())continue;Vec3d at=Vec3d.ofBottomCenter(foot);Box box=getBoundingBox().offset(at.subtract(getPos()));double distance=at.squaredDistanceTo(getPos());if(distance<best&&loadedBox(box)&&getWorld().isSpaceEmpty(this,box)&&getWorld().getWorldBorder().contains(box)){landingTarget=at;best=distance;}}}
    private void pack(){var m=record();if(m==null)return;m.state="guardada";m.health=getHealth();m.entity="";Expansion.store.save();discard();}
    @Override public boolean damage(DamageSource source,float amount){boolean result=super.damage(source,amount);if(result&&!getWorld().isClient){var m=record();if(m!=null){m.damageAt=System.currentTimeMillis();m.health=getHealth();Expansion.store.save();}animationDamage=10;}return result;}
    @Override public void onDeath(DamageSource source){if(!getWorld().isClient){var m=record();if(m!=null){m.state="muerta";m.health=0;Expansion.store.save();}removeAllPassengers();}super.onDeath(source);}
    @Override public void onRemoved(){if(!getWorld().isClient&&getRemovalReason()==RemovalReason.DISCARDED){var m=record();if(m!=null&&m.state.equals("activa")&&getUuidAsString().equals(m.entity)){m.state=m.temporary?"muerta":"guardada";m.health=getHealth();m.entity="";Expansion.store.save();}}super.onRemoved();}
    @Override protected void initGoals(){}
    @Override public boolean canUsePortals(){return false;}
    @Override public double getMountedHeightOffset(){return tier()==1?1.25:tier()==2?1.45:1.85;}
    @Override protected void updatePostDeath(){if(++deathTime>=60)remove(RemovalReason.KILLED);}
    @Override public void writeCustomDataToNbt(NbtCompound n){super.writeCustomDataToNbt(n);n.putString("CrystalMount",mountId);n.putInt("CrystalTier",tier());n.putBoolean("CrystalLanding",landing);}
    @Override public void readCustomDataFromNbt(NbtCompound n){super.readCustomDataFromNbt(n);mountId=n.getString("CrystalMount");dataTracker.set(TIER,ExpansionRules.tier(n.getInt("CrystalTier")));getAttributeInstance(EntityAttributes.GENERIC_MAX_HEALTH).setBaseValue(ExpansionRules.HEALTH[tier()-1]);setHealth(n.getFloat("Health"));landing=n.getBoolean("CrystalLanding");}
    @Override public AnimatableInstanceCache getAnimatableInstanceCache(){return cache;}
    @Override public void registerControllers(AnimatableManager.ControllerRegistrar r){r.add(new AnimationController<>(this,"body",4,s->{String clip=isDead()?"death":state()==3?"hurt":state()==2?"boost":state()==1?"fly":state()==4?"land":"idle";return s.setAndContinue(clip.equals("death")||clip.equals("hurt")||clip.equals("land")?RawAnimation.begin().thenPlay("animation.mount."+clip):RawAnimation.begin().thenLoop("animation.mount."+clip));}));}
}
