package net.tecnihardcore;
import net.fabricmc.fabric.api.client.networking.v1.*;
import net.fabricmc.fabric.api.client.rendering.v1.*;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.widget.ButtonWidget;
import net.minecraft.text.Text;
import net.minecraft.util.math.BlockPos;
public final class EventPresentation {
    static String id="",type="";static boolean practice,started,ready;static java.util.List<String> participants=java.util.List.of();static int age,count,wave,checkpoint,lap;static float nucleus;static BlockPos center=BlockPos.ORIGIN;static long received;
    public static void init(){
        ClientPlayNetworking.registerGlobalReceiver(EventDirector.CHANNEL,(c,h,b,r)->{boolean panel=b.readBoolean(),exists=b.readBoolean();String run=exists?b.readString(64):"",t=exists?b.readString(32):"";boolean pr=exists&&b.readBoolean(),st=exists&&b.readBoolean(),rd=exists&&b.readBoolean();int a=exists?b.readVarInt():0;BlockPos pos=exists?b.readBlockPos():BlockPos.ORIGIN;int n=exists?b.readVarInt():0,w=exists?b.readVarInt():0;float life=exists?b.readFloat():0;int check=exists?b.readVarInt():0,l=exists?b.readVarInt():0;int size=exists?b.readVarInt():0;if(size<0||size>1000)return;var names=new java.util.ArrayList<String>();for(int i=0;i<size;i++)names.add(b.readString(64));c.execute(()->{id=run;type=t;practice=pr;started=st;ready=rd;participants=names;age=a;center=pos;count=n;wave=w;nucleus=life;checkpoint=check;lap=l;received=c.world==null?0:c.world.getTime();if(panel)c.setScreen(new Panel());});});
        ClientPlayConnectionEvents.DISCONNECT.register((h,c)->id="");
        HudRenderCallback.EVENT.register((draw,delta)->{var c=MinecraftClient.getInstance();if(c.world==null||c.world.getRegistryKey()!=EventDirector.DIMENSION||id.isEmpty()||c.options.hudHidden)return;int time=age+(int)(c.world.getTime()-received);String line=!started?"INSCRIPCIÓN ABIERTA":time<0?"COMIENZA EN "+((-time+19)/20)+" s":type.equals("circuito")?"Vuelta "+Math.min(3,lap+1)+" / 3 · Anillo "+(checkpoint+1)+" / 12":type.equals("defensa")?"Oleada "+wave+" / 5 · Núcleo "+Math.max(0,(int)nucleus)+" / 200":"Etapa "+Math.min(3,time/4000+1)+" / 3 · "+Math.max(0,(12000-time)/20)+" s";draw.drawCenteredTextWithShadow(c.textRenderer,(practice?"ENSAYO":"HARDCORE")+" · "+type.toUpperCase(),draw.getScaledWindowWidth()/2,14,practice?0x8fdce8:0xffa36a);draw.drawCenteredTextWithShadow(c.textRenderer,line,draw.getScaledWindowWidth()/2,28,0xffffff);if(type.equals("tormenta")&&c.player!=null){double best=Double.MAX_VALUE;String direction="";for(int x:new int[]{-26,26})for(int z:new int[]{-26,26}){double distance=c.player.getPos().distanceTo(net.minecraft.util.math.Vec3d.ofBottomCenter(center).add(x,0,z));if(distance<best){best=distance;direction=(z<0?"N":"S")+(x<0?"O":"E");}}draw.drawCenteredTextWithShadow(c.textRenderer,"Refugio próximo: "+direction+" · "+(int)best+" bloques",draw.getScaledWindowWidth()/2,42,0xebd89d);}if(type.equals("circuito")&&(checkpoint==3||checkpoint==7||checkpoint==10))draw.drawCenteredTextWithShadow(c.textRenderer,"CORRIENTE: mantén el rumbo hacia el anillo iluminado",draw.getScaledWindowWidth()/2,42,0xebd89d);});
    }
    private static void action(String a,String type,boolean practice){var b=net.fabricmc.fabric.api.networking.v1.PacketByteBufs.create();b.writeString(a);b.writeString(type);b.writeBoolean(practice);ClientPlayNetworking.send(EventDirector.ACTION,b);}
    static final class Panel extends Screen {
        private boolean mode=true;private int ticks;Panel(){super(Text.literal("Eventos TecniHardcore"));}
        @Override protected void init(){int x=width/2-140,y=height/2-55;addDrawableChild(ButtonWidget.builder(Text.literal("Modo: ENSAYO"),b->{mode=!mode;b.setMessage(Text.literal("Modo: "+(mode?"ENSAYO":"HARDCORE")));}).dimensions(x,y,280,20).build());for(int i=0;i<3;i++){final String type=EventDirector.TYPES[i];addDrawableChild(ButtonWidget.builder(Text.literal("Preparar "+type),b->{action("prepare",type,mode);action("refresh","",mode);}).dimensions(x,y+26+i*24,280,20).build());}addDrawableChild(ButtonWidget.builder(Text.literal("INICIAR"),b->{action("start","",mode);action("refresh","",mode);}).dimensions(x,y+106,134,20).build());addDrawableChild(ButtonWidget.builder(Text.literal("DETENER"),b->{action("stop","",mode);action("refresh","",mode);}).dimensions(x+146,y+106,134,20).build());}
        @Override public void tick(){if(++ticks%20==0)action("refresh","",mode);}
        @Override public void render(DrawContext d,int mx,int my,float delta){renderBackground(d);super.render(d,mx,my,delta);d.drawCenteredTextWithShadow(textRenderer,title,width/2,height/2-100,0xe9d79c);d.drawCenteredTextWithShadow(textRenderer,id.isEmpty()?"Sin evento preparado":type+" · "+count+" inscritos · "+(practice?"Ensayo":"Hardcore")+" · "+(ready?(started?"EN CURSO":"LISTO"):"CONSTRUYENDO"),width/2,height/2-80,0xffffff);if(!participants.isEmpty())d.drawCenteredTextWithShadow(textRenderer,String.join(", ",participants).substring(0,Math.min(70,String.join(", ",participants).length())),width/2,height/2+73,0xffffff);if(!id.isEmpty())d.drawCenteredTextWithShadow(textRenderer,"/tecni evento entrar "+id,width/2,height/2+93,0x8fdce8);}
        @Override public boolean shouldPause(){return false;}
    }
}
