package net.tecnihardcore;

import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.*;
import net.fabricmc.fabric.api.entity.event.v1.*;
import net.fabricmc.fabric.api.event.player.*;
import net.fabricmc.fabric.api.networking.v1.*;
import net.minecraft.block.Blocks;
import net.minecraft.entity.*;
import net.minecraft.entity.mob.*;
import net.minecraft.item.*;
import net.minecraft.nbt.*;
import net.minecraft.registry.*;
import net.minecraft.server.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.*;
import net.minecraft.util.math.*;
import net.minecraft.world.*;
import java.nio.file.*;
import java.util.*;
import static net.minecraft.server.command.CommandManager.*;
import com.mojang.brigadier.arguments.StringArgumentType;

/** Events never edit the Overworld. Recovery snapshots exist before teleport or equipment changes. */
public final class EventDirector {
    public static final RegistryKey<World> DIMENSION=RegistryKey.of(RegistryKeys.WORLD,Hardcore.id("eventos"));
    public static final Identifier CHANNEL=Hardcore.id("event_v1"),ACTION=Hardcore.id("event_action_v1");
    public static final Item TROPHY=Registry.register(Registries.ITEM,Hardcore.id("trofeo_evento"),new Item(new Item.Settings().maxCount(1).fireproof()));
    public static final String[] TYPES={"tormenta","circuito","defensa"};
    private static final class Player {UUID id;boolean practice,eliminated;int checkpoint,lap,finish;Player(UUID id,boolean p){this.id=id;practice=p;}}
    private record Placement(BlockPos pos,net.minecraft.block.BlockState state){}
    private static final class Run {java.util.Deque<Placement> build=new java.util.ArrayDeque<>();boolean ready;String id=UUID.randomUUID().toString(),type;boolean practice,started;int age,wave,killed,spawned;float nucleus=200;BlockPos center;ServerWorld world;Map<UUID,Player> players=new LinkedHashMap<>();List<UUID> mobs=new ArrayList<>();Run(String t,boolean p,ServerWorld w,BlockPos pos){type=t;practice=p;world=w;center=pos;}}
    private static Run run;private static Path recovery;private static boolean restoring;private static final List<Entity> cleanup=new ArrayList<>();
    public static boolean reservesHazard(){return run!=null&&run.type.equals("tormenta");}
    public static boolean participant(ServerPlayerEntity p){return run!=null&&run.players.containsKey(p.getUuid());}
    public static boolean practice(ServerPlayerEntity p){return participant(p)&&run.practice&&!restoring;}
    public static boolean temporary(net.minecraft.entity.player.PlayerEntity p){return p instanceof ServerPlayerEntity sp&&practice(sp);}
    public static void init(){
        ServerLifecycleEvents.SERVER_STARTED.register(s->{recovery=s.getSavePath(WorldSavePath.ROOT).resolve("tecni-event-recovery");try{Files.createDirectories(recovery);}catch(Exception e){throw new IllegalStateException(e);}run=null;cleanup.clear();for(var p:s.getPlayerManager().getPlayerList())recover(p);});
        ServerLifecycleEvents.SERVER_STOPPING.register(s->{if(run!=null)cancel();});
        // Restore temporary event equipment before recovering any interrupted reward delivery.
        ServerPlayConnectionEvents.JOIN.register((h,sender,s)->{if(recovery!=null)recover(h.player);if(Expansion.store!=null&&!h.player.isDisconnected())Rewards.recover(h.player);});
        ServerPlayConnectionEvents.DISCONNECT.register((h,s)->{if(participant(h.player))leave(h.player,false);});
        ServerEntityEvents.ENTITY_LOAD.register((entity,w)->{if(w.getRegistryKey()!=DIMENSION)return;if(run==null&&entity.getCommandTags().stream().anyMatch(t->t.startsWith("TecniEvent:")))cleanup.add(entity);else if(run!=null&&entity instanceof net.minecraft.entity.projectile.ProjectileEntity projectile&&projectile.getOwner() instanceof ServerPlayerEntity p&&participant(p)){entity.addCommandTag("TecniEvent:"+run.id);if(run.practice&&entity instanceof net.minecraft.entity.projectile.PersistentProjectileEntity arrow)arrow.pickupType=net.minecraft.entity.projectile.PersistentProjectileEntity.PickupPermission.DISALLOWED;}});
        ServerLivingEntityEvents.ALLOW_DEATH.register((entity,source,amount)->{if(entity instanceof ServerPlayerEntity p&&practice(p)){var player=run.players.get(p.getUuid());player.eliminated=true;p.setHealth(20);p.clearStatusEffects();p.teleport(run.world,run.center.getX()+.5,68,run.center.getZ()+.5,0,0);p.changeGameMode(GameMode.SPECTATOR);p.sendMessage(Text.literal("Derrotado en ensayo. Tus vidas reales están intactas."),false);return false;}return true;});
        ServerLivingEntityEvents.AFTER_DEATH.register((entity,source)->{if(entity instanceof ServerPlayerEntity p&&participant(p)&&!run.practice){run.players.get(p.getUuid()).eliminated=true;}if(run!=null&&entity.getCommandTags().contains("TecniEvent:"+run.id)){run.killed++;run.mobs.remove(entity.getUuid());}});
        PlayerBlockBreakEvents.BEFORE.register((w,p,pos,state,be)->w.getRegistryKey()!=DIMENSION||p.hasPermissionLevel(4)&&!participant((ServerPlayerEntity)p));
        UseBlockCallback.EVENT.register((p,w,hand,hit)->w.getRegistryKey()==DIMENSION?ActionResult.FAIL:ActionResult.PASS);
        UseItemCallback.EVENT.register((p,w,hand)->{var item=p.getStackInHand(hand).getItem();if(p instanceof ServerPlayerEntity sp&&practice(sp)&&item!=Items.DIAMOND_SWORD&&item!=Items.COOKED_BEEF&&item!=Items.BOW&&item!=Items.SHIELD)return TypedActionResult.fail(p.getStackInHand(hand));return w.getRegistryKey()==DIMENSION&&(item instanceof BlockItem||item instanceof BucketItem||item==Items.ENDER_PEARL||item==Items.CHORUS_FRUIT||item==Items.FLINT_AND_STEEL)?TypedActionResult.fail(p.getStackInHand(hand)):TypedActionResult.pass(p.getStackInHand(hand));});
        ServerTickEvents.END_SERVER_TICK.register(s->tick());
        ServerPlayNetworking.registerGlobalReceiver(ACTION,(s,p,h,b,r)->{String action=b.readString(16),type=b.readString(16);boolean practice=b.readBoolean();s.execute(()->{if(!AuthBootstrap.authenticated(p)||!p.hasPermissionLevel(4))return;switch(action){case "prepare"->prepare(p.getCommandSource(),type,practice);case "start"->{if(run!=null)start(p.getCommandSource(),run.id);}case "stop"->{if(run!=null)cancel();}case "refresh"->send(p,false);}});});
        CommandRegistrationCallback.EVENT.register((d,a,e)->{
            var root=literal("evento");var prepare=literal("preparar").requires(s->s.hasPermissionLevel(4));for(String type:TYPES)for(String mode:new String[]{"ensayo","hardcore"})prepare.then(literal(type).then(literal(mode).executes(c->prepare(c.getSource(),type,mode.equals("ensayo")))));
            root.then(prepare).then(literal("panel").requires(s->s.hasPermissionLevel(4)).executes(c->{panel(c.getSource().getPlayerOrThrow());return 1;}))
                .then(literal("listar").executes(c->{c.getSource().sendFeedback(()->Text.literal(run==null?"No hay eventos preparados.":description()),false);return run==null?0:1;}))
                .then(literal("iniciar").requires(s->s.hasPermissionLevel(4)).then(argument("id",StringArgumentType.word()).executes(c->start(c.getSource(),StringArgumentType.getString(c,"id")))))
                .then(literal("detener").requires(s->s.hasPermissionLevel(4)).then(argument("id",StringArgumentType.word()).executes(c->{if(run==null||!run.id.equals(StringArgumentType.getString(c,"id")))return 0;cancel();return 1;})))
                .then(literal("entrar").then(argument("id",StringArgumentType.word()).executes(c->join(c.getSource().getPlayerOrThrow(),StringArgumentType.getString(c,"id")))))
                .then(literal("salir").executes(c->{leave(c.getSource().getPlayerOrThrow(),false);return 1;}));d.register(literal("tecni").then(root));
        });
    }
    private static String description(){return run.type+" · "+run.id+" · "+(run.practice?"ENSAYO: sin pérdidas ni premios":"HARDCORE: vidas e inventario reales")+" · "+run.players.size()+" participantes · "+(run.ready?"LISTO":"PREPARANDO ARENA");}
    private static int prepare(net.minecraft.server.command.ServerCommandSource source,String type,boolean practice){if(run!=null){source.sendError(Text.literal("Detén o termina el evento actual primero."));return 0;}if(!Arrays.asList(TYPES).contains(type))return 0;var w=source.getServer().getWorld(DIMENSION);if(w==null){source.sendError(Text.literal("La dimensión de eventos no está instalada."));return 0;}
        try{Path path=recovery.resolve("next-plot.txt");int plot=Files.exists(path)?Integer.parseInt(Files.readString(path).trim()):0;if(plot>=10000)throw new IllegalStateException("Event plots exhausted");Files.writeString(path,Integer.toString(plot+1));BlockPos center=new BlockPos(plot*512,65,0);for(int x=-64;x<=64;x++)for(int z=-64;z<=64;z++)if(w.getTopY(Heightmap.Type.WORLD_SURFACE,center.getX()+x,z)>w.getBottomY())throw new IllegalStateException("La parcela está ocupada: no se modifica.");
            var candidate=new Run(type,practice,w,center);build(candidate);run=candidate;source.sendFeedback(()->Text.literal("Preparado: "+description()+". Entrar con /tecni evento entrar "+run.id),true);Hardcore.LOG.warn("ADMIN {} prepared event {}",source.getName(),description());source.getServer().getPlayerManager().broadcast(Text.literal("EVENTO · "+description()+". Espera a que la arena esté lista; inscripción explícita con /tecni evento entrar "+run.id),false);return 1;
        }catch(Exception ex){source.sendError(Text.literal("No se pudo preparar: "+ex.getMessage()));return 0;}}
    private static void build(Run r){int cx=r.center.getX();for(int x=-64;x<=64;x++)for(int z=-64;z<=64;z++){boolean edge=Math.abs(x)==64||Math.abs(z)==64;r.build.add(new Placement(new BlockPos(cx+x,64,z),edge?Blocks.POLISHED_BLACKSTONE_BRICKS.getDefaultState():((x%8==0||z%8==0)?Blocks.CUT_COPPER:Blocks.DEEPSLATE_TILES).getDefaultState()));if(edge)for(int y=65;y<69;y++)r.build.add(new Placement(new BlockPos(cx+x,y,z),Blocks.POLISHED_BLACKSTONE_WALL.getDefaultState()));}
        for(int x:new int[]{-26,26})for(int z:new int[]{-26,26})for(int dx=-4;dx<=4;dx++)for(int dz=-4;dz<=4;dz++){r.build.add(new Placement(new BlockPos(cx+x+dx,70,z+dz),Blocks.WAXED_CUT_COPPER.getDefaultState()));if(Math.abs(dx)==4&&Math.abs(dz)==4)for(int y=65;y<=69;y++)r.build.add(new Placement(new BlockPos(cx+x+dx,y,z+dz),Blocks.DEEPSLATE_BRICKS.getDefaultState()));}
        if(r.type.equals("circuito"))for(int i:new int[]{1,4,7,10}){double a=(i+.5)*Math.PI/6;int x=cx+(int)(Math.cos(a)*36),z=(int)(Math.sin(a)*36),base=74+(i%3)*6;for(int y=base;y<base+8;y++)r.build.add(new Placement(new BlockPos(x,y,z),y==base+7?Blocks.SEA_LANTERN.getDefaultState():Blocks.AMETHYST_BLOCK.getDefaultState()));}
        for(int y=65;y<=70;y++)r.build.add(new Placement(r.center.withY(y),y==70?Blocks.SEA_LANTERN.getDefaultState():Blocks.CRYING_OBSIDIAN.getDefaultState()));

    }
    private static Path file(UUID id){return recovery.resolve(id+".nbt");}
    private static int join(ServerPlayerEntity p,String id){if(run==null||!run.ready||run.started||!run.id.equals(id)||participant(p)||!AuthBootstrap.authenticated(p)||Hardcore.soul(p).lives<=0||p.hasVehicle()||p.currentScreenHandler!=p.playerScreenHandler||!p.currentScreenHandler.getCursorStack().isEmpty())return 0;for(var m:Expansion.store.data.mounts.values())if(!m.temporary&&m.state.equals("activa")&&m.holder.equals(p.getUuidAsString())){p.sendMessage(Text.literal("Guarda tu montura antes de entrar al evento."),false);return 0;}
        try{if(Files.exists(file(p.getUuid()))){recover(p);if(Files.exists(file(p.getUuid())))return 0;}NbtCompound n=new NbtCompound();n.putString("eventId",run.id);n.putString("eventType",run.type);n.putString("dimension",p.getWorld().getRegistryKey().getValue().toString());n.putDouble("x",p.getX());n.putDouble("y",p.getY());n.putDouble("z",p.getZ());n.putFloat("yaw",p.getYaw());n.putFloat("pitch",p.getPitch());n.putString("mode",p.interactionManager.getGameMode().getName());n.putBoolean("practice",run.practice);n.putFloat("health",p.getHealth());n.putInt("food",p.getHungerManager().getFoodLevel());n.putFloat("saturation",p.getHungerManager().getSaturationLevel());n.putInt("level",p.experienceLevel);n.putInt("total",p.totalExperience);n.putFloat("progress",p.experienceProgress);n.put("fullPlayer",p.writeNbt(new NbtCompound()));n.put("inventory",p.getInventory().writeNbt(new NbtList()));NbtList effects=new NbtList();for(var effect:p.getStatusEffects())effects.add(effect.writeNbt(new NbtCompound()));n.put("effects",effects);Path tmp=file(p.getUuid()).resolveSibling(p.getUuid()+".tmp");NbtIo.writeCompressed(n,tmp.toFile());try(var channel=java.nio.channels.FileChannel.open(tmp,StandardOpenOption.WRITE)){channel.force(true);}Files.move(tmp,file(p.getUuid()),StandardCopyOption.ATOMIC_MOVE);run.players.put(p.getUuid(),new Player(p.getUuid(),run.practice));
            if(run.practice){p.getInventory().clear();p.clearStatusEffects();p.setHealth(20);p.getHungerManager().setFoodLevel(20);p.equipStack(EquipmentSlot.HEAD,new ItemStack(Items.DIAMOND_HELMET));p.equipStack(EquipmentSlot.CHEST,new ItemStack(Items.DIAMOND_CHESTPLATE));p.equipStack(EquipmentSlot.LEGS,new ItemStack(Items.DIAMOND_LEGGINGS));p.equipStack(EquipmentSlot.FEET,new ItemStack(Items.DIAMOND_BOOTS));p.getInventory().setStack(0,new ItemStack(Items.DIAMOND_SWORD));p.getInventory().setStack(1,new ItemStack(Items.COOKED_BEEF,32));p.getInventory().setStack(2,new ItemStack(Items.BOW));p.getInventory().setStack(3,new ItemStack(Items.ARROW,64));p.equipStack(EquipmentSlot.OFFHAND,new ItemStack(Items.SHIELD));}
            p.changeGameMode(GameMode.SURVIVAL);p.teleport(run.world,run.center.getX()+8.5,65,8.5,0,0);p.sendMessage(Text.literal(description()),false);return 1;
        }catch(Exception ex){Hardcore.LOG.error("Event enrollment failed",ex);recover(p);return 0;}}
    private static int start(net.minecraft.server.command.ServerCommandSource source,String id){if(run==null||!run.ready||run.started||!run.id.equals(id)||run.players.isEmpty())return 0;run.started=true;run.age=-200;Hardcore.LOG.warn("ADMIN {} started event {}",source.getName(),description());if(run.type.equals("circuito"))for(var player:run.players.values()){var p=source.getServer().getPlayerManager().getPlayer(player.id);if(p!=null)CrystalMount.eventMount(p,run.id);}return 1;}
    private static void tick(){for(var entity:new ArrayList<>(cleanup))if(!entity.isRemoved())entity.discard();cleanup.clear();if(run==null)return;var r=run;if(!r.ready){for(int i=0;i<256&&!r.build.isEmpty();i++){var block=r.build.removeFirst();if(!r.world.getBlockState(block.pos).isAir()){Hardcore.LOG.error("Event construction canceled: occupied position {}",block.pos);cancel();return;}r.world.setBlockState(block.pos,block.state,2);}if(r.build.isEmpty()){r.ready=true;Hardcore.LOG.info("Event arena ready: {}",r.id);}return;}for(var player:new ArrayList<>(r.players.values())){var p=r.world.getServer().getPlayerManager().getPlayer(player.id);if(p==null)continue;if(r.practice&&p.currentScreenHandler!=p.playerScreenHandler)p.closeHandledScreen();if(player.eliminated){if(!r.practice&&!p.isDead())leave(p,false);continue;}if(p.getWorld()!=r.world){leave(p,false);continue;}if(p.getX()<r.center.getX()-64||p.getX()>r.center.getX()+64||Math.abs(p.getZ())>64||p.getY()<50||p.getY()>300){p.stopRiding();p.teleport(r.world,r.center.getX()+8.5,65,8.5,0,0);}}
        if(!r.started){if(r.world.getTime()%20==0)broadcast();return;}if(r.players.isEmpty()||r.players.values().stream().allMatch(p->p.eliminated)){cancel();return;}r.age++;if(r.age<0){if(r.age%20==0)broadcast();return;}
        if(r.type.equals("tormenta")){if(r.age==0||r.age==4000||r.age==8000){for(var h:new ArrayList<>(Cataclysms.active.values()))if(h.world==r.world)Cataclysms.stop(h);try{Cataclysms.start(r.world,r.age==0?2:r.age==4000?1:0,r.center,64,200);}catch(IllegalArgumentException blocked){Hardcore.LOG.warn("Event hazard cannot start: {}",blocked.getMessage());cancel();return;}}if(r.age>=12000){finish();return;}}
        if(r.type.equals("circuito")){for(var player:r.players.values()){var p=r.world.getServer().getPlayerManager().getPlayer(player.id);if(p==null||player.eliminated||player.finish>0)continue;Vec3d ring=ring(r,player.checkpoint);if(p.getVehicle() instanceof CrystalMount mount&&(player.checkpoint==3||player.checkpoint==7||player.checkpoint==10)&&p.getPos().distanceTo(ring)<12){mount.addVelocity(Math.sin(r.age*.08)*.045,.008,Math.cos(r.age*.08)*.045);mount.velocityModified=true;}if(p.getVehicle() instanceof CrystalMount&&p.getPos().distanceTo(ring)<3.5){player.checkpoint++;if(player.checkpoint==12){player.checkpoint=0;player.lap++;if(player.lap==3){player.finish=r.age+1;p.sendMessage(Text.literal("Carrera completada en "+(player.finish/20.0)+" s."),false);}}}}if(r.age>=12000||r.players.values().stream().allMatch(p->p.eliminated||p.finish>0)){finish();return;}}
        if(r.type.equals("defensa")){r.mobs.removeIf(id->r.world.getEntity(id)==null||!r.world.getEntity(id).isAlive());if(r.mobs.isEmpty()){if(r.wave==5){finish();return;}if(r.age%100==0)wave(r);}if(r.age%20==0)for(UUID id:r.mobs){var e=r.world.getEntity(id);if(e instanceof HostileEntity m){var player=r.world.getPlayers(p->r.players.containsKey(p.getUuid())&&!r.players.get(p.getUuid()).eliminated&&!p.isSpectator()).stream().min(Comparator.comparingDouble(m::squaredDistanceTo)).orElse(null);if(player!=null&&m.squaredDistanceTo(player)<64)m.setTarget(player);else{m.setTarget(null);m.getNavigation().startMovingTo(r.center.getX()+.5,65,r.center.getZ()+.5,1);if(m.squaredDistanceTo(Vec3d.ofBottomCenter(r.center))<9)r.nucleus-=8;}}}if(r.nucleus<=0){cancel();return;}}
        if(r.players.isEmpty()||r.players.values().stream().allMatch(p->p.eliminated)){cancel();return;}if(r.age%20==0)broadcast();
    }
    public static Vec3d ringPosition(BlockPos center,int i){double a=i*Math.PI/6;return Vec3d.ofBottomCenter(center).add(Math.cos(a)*40,8+(i%3)*8,Math.sin(a)*40);}
    private static Vec3d ring(Run r,int i){return ringPosition(r.center,i);}
    private static void wave(Run r){r.wave++;int amount=ExpansionRules.waveSize(r.players.size());for(int i=0;i<amount;i++){double a=2*Math.PI*i/amount;HostileEntity mob=i%3==0?(r.wave>=3?new StrayEntity(EntityType.STRAY,r.world):new SkeletonEntity(EntityType.SKELETON,r.world)):(r.wave>=2&&i%2==0?new HuskEntity(EntityType.HUSK,r.world):new ZombieEntity(EntityType.ZOMBIE,r.world));mob.setPersistent();mob.addCommandTag("TecniEvent:"+r.id);mob.refreshPositionAndAngles(r.center.getX()+Math.cos(a)*48,65,Math.sin(a)*48,0,0);mob.initialize(r.world,r.world.getLocalDifficulty(mob.getBlockPos()),SpawnReason.EVENT,null,null);mob.equipStack(EquipmentSlot.HEAD,new ItemStack(r.wave>=4?Items.DIAMOND_HELMET:Items.IRON_HELMET));if(r.wave>=3&&mob instanceof ZombieEntity)mob.equipStack(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SWORD));for(EquipmentSlot slot:EquipmentSlot.values())mob.setEquipmentDropChance(slot,0);if(r.world.spawnEntity(mob))r.mobs.add(mob.getUuid());}}
    private static void finish(){if(run==null)return;Run r=run;var winners=r.players.values().stream().filter(p->!p.eliminated&&(!r.type.equals("circuito")||p.finish>0)).sorted(Comparator.comparingInt(p->p.finish)).toList();int rank=0;for(var winner:winners){var p=r.world.getServer().getPlayerManager().getPlayer(winner.id);if(p!=null&&!r.practice){int diamonds=r.type.equals("circuito")?(rank==0?6:rank==1?3:rank==2?1:0):4;String trophy=!r.type.equals("circuito")||rank==0?"Trofeo · "+r.type:"";if(diamonds>0)Rewards.event(r.id,p,diamonds,trophy);}rank++;}recordResult(r,"completo");for(var winner:winners){var p=r.world.getServer().getPlayerManager().getPlayer(winner.id);if(p!=null)p.sendMessage(Text.literal("Evento completado · "+r.type+" · "+(r.practice?"ENSAYO sin premios":"Reclama tu premio con /tecni recompensas")+(r.type.equals("circuito")?" · Tiempo "+(winner.finish/20.0)+" s":"")),false);}cancel();}
    private static void recordResult(Run r,String status){try{Path directory=recovery.resolve("results");Files.createDirectories(directory);Path file=directory.resolve(r.id+".json");if(Files.exists(file))return;var result=new com.google.gson.JsonObject();result.addProperty("id",r.id);result.addProperty("type",r.type);result.addProperty("mode",r.practice?"ensayo":"hardcore");result.addProperty("status",status);result.addProperty("seconds",Math.max(0,r.age/20));result.addProperty("recordedAt",java.time.Instant.now().toString());var participants=new com.google.gson.JsonArray();for(var entry:r.players.values()){var player=new com.google.gson.JsonObject();player.addProperty("uuid",entry.id.toString());player.addProperty("eliminated",entry.eliminated);player.addProperty("laps",entry.lap);player.addProperty("finishTicks",entry.finish);participants.add(player);}result.add("participants",participants);Path tmp=file.resolveSibling(file.getFileName()+".tmp");Files.writeString(tmp,new com.google.gson.GsonBuilder().setPrettyPrinting().create().toJson(result),java.nio.charset.StandardCharsets.UTF_8);try(var channel=java.nio.channels.FileChannel.open(tmp,StandardOpenOption.WRITE)){channel.force(true);}Files.move(tmp,file,StandardCopyOption.ATOMIC_MOVE);}catch(Exception error){throw new IllegalStateException("Cannot record event result; recovery retained",error);}}
    private static void leave(ServerPlayerEntity p,boolean completed){if(run!=null)run.players.remove(p.getUuid());p.stopRiding();CrystalMount.retireTemporary(p);recover(p);}
    private static void cancel(){if(run==null)return;Run r=run;recordResult(r,"cancelado");for(var h:new ArrayList<>(Cataclysms.active.values()))if(h.world==r.world)Cataclysms.stop(h);for(var p:new ArrayList<>(r.players.values())){var player=r.world.getServer().getPlayerManager().getPlayer(p.id);if(player!=null)leave(player,false);}var entities=new ArrayList<Entity>();r.world.iterateEntities().forEach(entities::add);for(var e:entities)if(e.getCommandTags().contains("TecniEvent:"+r.id))e.discard();run=null;for(var p:r.world.getServer().getPlayerManager().getPlayerList())if(ServerPlayNetworking.canSend(p,CHANNEL))send(p,false);Hardcore.LOG.info("Event {} ended; pending offline snapshots retained",r.id);}
    public static void recover(ServerPlayerEntity p){if(recovery==null||!Files.exists(file(p.getUuid())))return;restoring=true;try{var n=NbtIo.readCompressed(file(p.getUuid()).toFile());if(n==null)throw new IllegalStateException("Empty snapshot");if(n.getBoolean("practice")){p.stopRiding();if(n.contains("fullPlayer"))p.readNbt(n.getCompound("fullPlayer"));p.getInventory().clear();p.getInventory().readNbt(n.getList("inventory",10));p.clearStatusEffects();for(var value:n.getList("effects",10)){var effect=net.minecraft.entity.effect.StatusEffectInstance.fromNbt((NbtCompound)value);if(effect!=null)p.addStatusEffect(effect);}p.setHealth(Math.min(p.getMaxHealth(),Math.max(1,n.getFloat("health"))));p.getHungerManager().setFoodLevel(n.getInt("food"));p.getHungerManager().setSaturationLevel(n.getFloat("saturation"));p.experienceLevel=n.getInt("level");p.totalExperience=n.getInt("total");p.experienceProgress=n.getFloat("progress");}
            var world=p.getServer().getWorld(RegistryKey.of(RegistryKeys.WORLD,new Identifier(n.getString("dimension"))));if(world==null)world=p.getServer().getOverworld();Vec3d exit=new Vec3d(n.getDouble("x"),n.getDouble("y"),n.getDouble("z"));if(!safeExit(world,p,exit)){BlockPos spawn=world.getSpawnPos();Vec3d found=null;for(BlockPos pos:BlockPos.iterate(spawn.add(-8,-3,-8),spawn.add(8,4,8)))if(safeExit(world,p,Vec3d.ofBottomCenter(pos))){found=Vec3d.ofBottomCenter(pos);break;}if(found==null)throw new IllegalStateException("No safe return position: recovery retained");exit=found;}p.teleport(world,exit.x,exit.y,exit.z,n.getFloat("yaw"),n.getFloat("pitch"));p.changeGameMode(Hardcore.soul(p).lives==0?GameMode.SPECTATOR:GameMode.byName(n.getString("mode"),GameMode.SURVIVAL));p.getServer().getPlayerManager().saveAllPlayerData();Files.delete(file(p.getUuid()));p.currentScreenHandler.sendContentUpdates();
        }catch(Exception e){Hardcore.LOG.error("Cannot recover event inventory for {}: snapshot retained",p.getUuid(),e);p.networkHandler.disconnect(Text.literal("Tu sesión de evento requiere recuperación. El respaldo está conservado; avisa al administrador."));}finally{restoring=false;}}
    private static boolean safeExit(ServerWorld w,ServerPlayerEntity p,Vec3d at){BlockPos pos=BlockPos.ofFloored(at);return w.getWorldBorder().contains(pos)&&w.getBlockState(pos.down()).isSolidBlock(w,pos.down())&&w.getFluidState(pos).isEmpty()&&w.isSpaceEmpty(p,p.getBoundingBox().offset(at.subtract(p.getPos())));}
    private static void panel(ServerPlayerEntity p){send(p,true);}
    private static void broadcast(){if(run==null)return;for(var p:run.world.getServer().getPlayerManager().getPlayerList())if(run.players.containsKey(p.getUuid())||p.getWorld()==run.world&&p.squaredDistanceTo(Vec3d.ofBottomCenter(run.center))<128*128&&AuthBootstrap.authenticated(p))send(p,false);}
    private static void send(ServerPlayerEntity p,boolean panel){if(!ServerPlayNetworking.canSend(p,CHANNEL))return;var b=PacketByteBufs.create();b.writeBoolean(panel);b.writeBoolean(run!=null);if(run!=null){b.writeString(run.id);b.writeString(run.type);b.writeBoolean(run.practice);b.writeBoolean(run.started);b.writeBoolean(run.ready);b.writeVarInt(run.age);b.writeBlockPos(run.center);b.writeVarInt(run.players.size());b.writeVarInt(run.wave);b.writeFloat(run.nucleus);var player=run.players.get(p.getUuid());b.writeVarInt(player==null?0:player.checkpoint);b.writeVarInt(player==null?0:player.lap);b.writeVarInt(run.players.size());for(var enrolled:run.players.values()){var participant=p.getServer().getPlayerManager().getPlayer(enrolled.id);b.writeString(participant==null?enrolled.id.toString():participant.getName().getString());}}ServerPlayNetworking.send(p,CHANNEL,b);}
}
