package net.tecnihardcore;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.item.*;
import net.minecraft.nbt.*;
import java.util.*;

final class Market {
    static long balance(String id){return Social.store.data.wallets.getOrDefault(id,0L);}
    static boolean available(ServerPlayerEntity p){if(!Social.ready(p))return false;if(EventDirector.participant(p)||p.currentScreenHandler!=p.playerScreenHandler||!p.currentScreenHandler.getCursorStack().isEmpty()||p.isSpectator()||p.isCreative()||!p.isAlive()||Hardcore.soul(p).lives<=0||!CivicNpcs.nearMerchant(p)){Social.say(p,"Acércate a Selma, la mercader del spawn. Debes estar vivo para comerciar.");return false;}return true;}
    static ItemStack item(String nbt){try{return ItemStack.fromNbt(StringNbtReader.parse(nbt));}catch(Exception e){throw new IllegalStateException("Invalid escrow item",e);}}
    static boolean forbidden(ItemStack item){return item.isEmpty()||item.isOf(CrystalMount.TOKEN)||item.isOf(net.minecraft.item.Items.COMMAND_BLOCK)||item.isOf(net.minecraft.item.Items.BARRIER)||item.isOf(net.minecraft.item.Items.STRUCTURE_BLOCK)||item.hasNbt()&&(item.getNbt().contains("TecniEventSession")||item.getNbt().contains("TecniReward"));}
    static void sell(ServerPlayerEntity p,long price){if(!available(p))return;ItemStack held=p.getMainHandStack();if(held.writeNbt(new NbtCompound()).toString().length()>4096||forbidden(held)||price<1||price>1_000_000||Social.store.data.offers.values().stream().filter(o->o.seller.equals(p.getUuidAsString())&&o.state.equals("open")).count()>=10||Social.store.data.offers.values().stream().filter(o->o.state.equals("open")).count()>=300){Social.say(p,"Oferta inválida: precio 1–1.000.000, máximo 10 anuncios. No se venden monturas vinculadas ni objetos de sesión.");return;}var b=Social.store.copy();var offer=new SocialStore.Offer();offer.id=UUID.randomUUID().toString();offer.seller=p.getUuidAsString();offer.sellerName=p.getName().getString();offer.price=price;offer.item=held.writeNbt(new NbtCompound()).toString();offer.created=System.currentTimeMillis();b.offers.put(offer.id,offer);var after=p.getInventory().writeNbt(new NbtList());int slot=p.getInventory().selectedSlot;for(int i=after.size()-1;i>=0;i--)if((after.getCompound(i).getByte("Slot")&255)==slot)after.remove(i);Social.store.inventory(p,after,b,"market escrow "+offer.id);Social.say(p,"Oferta publicada por "+price+" Cristales Tecni. El lote completo quedó en custodia.");}
    static void buy(ServerPlayerEntity p,String id){if(!available(p))return;var offer=Social.store.data.offers.get(id);if(offer==null||!offer.state.equals("open")||offer.seller.equals(p.getUuidAsString())||balance(p.getUuidAsString())<offer.price){Social.say(p,"Oferta no disponible o saldo insuficiente.");return;}if(balance(offer.seller)>SocialRules.MAX_BALANCE-offer.price){Social.say(p,"El vendedor no puede recibir más saldo.");return;}var b=Social.store.copy();b.wallets.put(p.getUuidAsString(),SocialRules.transfer(balance(p.getUuidAsString()),-offer.price));b.wallets.put(offer.seller,SocialRules.transfer(balance(offer.seller),offer.price));b.offers.get(id).state="sold";var parcel=new SocialStore.Parcel();parcel.id=UUID.randomUUID().toString();parcel.owner=p.getUuidAsString();parcel.item=offer.item;parcel.reason="Compra a "+offer.sellerName;b.parcels.put(parcel.id,parcel);Social.store.commit(b,"market purchase "+id+" by "+p.getUuidAsString());Social.say(p,"Compra realizada. Retira el objeto en tu buzón; si no tenés espacio seguirá guardado.");var seller=p.getServer().getPlayerManager().getPlayer(UUID.fromString(offer.seller));if(seller!=null)Social.say(seller,"Vendiste un lote por "+offer.price+" Cristales Tecni.");}
    static void cancel(ServerPlayerEntity p,String id){if(!available(p))return;var offer=Social.store.data.offers.get(id);if(offer==null||!offer.state.equals("open")||!offer.seller.equals(p.getUuidAsString()))return;var b=Social.store.copy();b.offers.get(id).state="cancelled";var parcel=new SocialStore.Parcel();parcel.id=UUID.randomUUID().toString();parcel.owner=p.getUuidAsString();parcel.item=offer.item;parcel.reason="Oferta cancelada";b.parcels.put(parcel.id,parcel);Social.store.commit(b,"market cancel "+id);Social.say(p,"Oferta cancelada. El objeto está en tu buzón.");}
    static void withdraw(ServerPlayerEntity p,String id){if(!available(p))return;var parcel=Social.store.data.parcels.get(id);if(parcel==null||!parcel.owner.equals(p.getUuidAsString()))return;ItemStack wanted=item(parcel.item);var inv=new net.minecraft.inventory.SimpleInventory(36);for(int i=0;i<36;i++)inv.setStack(i,p.getInventory().getStack(i).copy());ItemStack rest=inv.addStack(wanted.copy());if(!rest.isEmpty()){Social.say(p,"No hay espacio para el lote completo. El buzón lo conserva.");return;}var after=p.getInventory().writeNbt(new NbtList());for(int i=after.size()-1;i>=0;i--)if((after.getCompound(i).getByte("Slot")&255)<36)after.remove(i);for(int i=0;i<36;i++)if(!inv.getStack(i).isEmpty()){var tag=inv.getStack(i).writeNbt(new NbtCompound());tag.putByte("Slot",(byte)i);after.add(tag);}var b=Social.store.copy();b.parcels.remove(id);Social.store.inventory(p,after,b,"market withdraw "+id);Social.say(p,"Lote retirado del buzón.");}
    private Market(){}
}
