package net.tecnihardcore;
import net.fabricmc.fabric.api.networking.v1.*;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.*;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.util.*;

final class NpcSkins {
    static final Identifier REQUEST=Hardcore.id("npc_skin_request_v1"),DATA=Hardcore.id("npc_skin_data_v1");
    private static final Map<UUID,Integer> last=new HashMap<>();
    private static Path directory(net.minecraft.server.MinecraftServer s){return s.getSavePath(WorldSavePath.ROOT).resolve("tecni-npc-skins");}
    static void init(){ServerPlayNetworking.registerGlobalReceiver(REQUEST,(s,p,h,b,r)->{String hash=b.readString(64);s.execute(()->{if(!AuthBootstrap.authenticated(p)||!hash.matches("[a-f0-9]{64}")||s.getTicks()-last.getOrDefault(p.getUuid(),-100)<5||CivicNpcs.definitions.values().stream().noneMatch(n->n.skinHash.equals(hash)))return;last.put(p.getUuid(),s.getTicks());try{Path skin=directory(s).resolve(hash+".png");if(Files.size(skin)>65536)return;byte[] png=Files.readAllBytes(skin);if(png.length>65536)return;var data=PacketByteBufs.create();data.writeString(hash);data.writeByteArray(png);ServerPlayNetworking.send(p,DATA,data);}catch(Exception e){Hardcore.LOG.warn("Missing NPC skin {}",hash);}});});}
    static void clear(){last.clear();}
    static void fetch(ServerPlayerEntity player,String id,String url){var n=CivicNpcs.definitions.get(id);if(n==null){Social.say(player,"NPC desconocido.");return;}URI uri;try{uri=URI.create(url);Set<String> hosts=new HashSet<>(Set.of("textures.minecraft.net","raw.githubusercontent.com","cdn.discordapp.com","media.discordapp.net"));Path config=player.getServer().getRunDirectory().toPath().resolve("config/tecnihardcore/npc-skin-hosts.txt");if(Files.exists(config))for(String line:Files.readAllLines(config))if(line.matches("[a-z0-9.-]{3,100}"))hosts.add(line);if(!uri.getScheme().equals("https")||uri.getUserInfo()!=null||uri.getFragment()!=null||uri.getPort()!=-1||!hosts.contains(uri.getHost()))throw new IllegalArgumentException();}catch(Exception error){Social.say(player,"Usa una URL HTTPS directa de textures.minecraft.net, GitHub raw o Discord. Otros dominios requieren añadirlos a npc-skin-hosts.txt.");return;}var server=player.getServer();UUID owner=player.getUuid();Social.say(player,"Descargando y verificando la skin 64×64...");java.util.concurrent.CompletableFuture.runAsync(()->{try{var client=HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(8)).followRedirects(HttpClient.Redirect.NEVER).build();var request=HttpRequest.newBuilder(uri).timeout(java.time.Duration.ofSeconds(12)).header("User-Agent","TecniHardcore-NPC/2.8.0").GET().build();var response=client.send(request,HttpResponse.BodyHandlers.ofInputStream());byte[] bytes;try(var body=response.body()){if(response.statusCode()!=200)throw new IllegalArgumentException("HTTP "+response.statusCode());bytes=body.readNBytes(65537);}if(bytes.length<24||bytes.length>65536||!Arrays.equals(Arrays.copyOf(bytes,8),new byte[]{(byte)137,80,78,71,13,10,26,10})||java.nio.ByteBuffer.wrap(bytes,16,8).getInt()!=64||java.nio.ByteBuffer.wrap(bytes,20,4).getInt()!=64)throw new IllegalArgumentException("Se requiere PNG de 64×64, máximo 64 KB");var image=javax.imageio.ImageIO.read(new java.io.ByteArrayInputStream(bytes));if(image==null)throw new IllegalArgumentException("PNG inválido");var sanitized=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"PNG",sanitized);byte[] png=sanitized.toByteArray();String hash=java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(png));Files.createDirectories(directory(server));Path target=directory(server).resolve(hash+".png");Files.write(target,png);server.execute(()->{var current=CivicNpcs.definitions.get(id);if(!server.isRunning()||current!=n)return;current.skinHash=hash;CivicNpcs.save();CivicNpcs.ensure();var p=server.getPlayerManager().getPlayer(owner);if(p!=null)Social.say(p,"Skin aplicada a "+current.name+".");});}catch(Exception e){server.execute(()->{var p=server.getPlayerManager().getPlayer(owner);if(p!=null)Social.say(p,"No se pudo cargar la skin: "+e.getMessage());});}});}
}
