const fs=require('fs'),path=require('path');
const MODES=['vanilla','optimized','ultra-optimized','juana-manso','quality','ultra-quality'];
const validName=name=>typeof name==='string'&&/^[A-Za-z0-9_]{3,16}$/.test(name);
class Settings {
 constructor(directory){this.file=path.join(directory,'settings.json');this.data={schema:1,username:'',ram:6,javaPath:'',gamePath:'',graphicsMode:null,graphicsPending:false};if(fs.existsSync(this.file)){try{Object.assign(this.data,JSON.parse(fs.readFileSync(this.file,'utf8')));}catch{throw Error('No se pudieron leer tus ajustes. Conserva settings.json antes de repararlo.');}}if(!validName(this.data.username))this.data.username='';}
 save(patch){const next={...this.data};for(const key of ['username','ram','javaPath','gamePath','graphicsMode','graphicsPending'])if(Object.hasOwn(patch,key))next[key]=patch[key];if(next.username&&!validName(next.username))throw Error('Usa un nombre de 3 a 16 letras, números o guiones bajos.');if(next.graphicsMode!==null&&!MODES.includes(next.graphicsMode))throw Error('Perfil gráfico desconocido.');next.ram=Math.min(16,Math.max(2,Number(next.ram)||6));for(const key of ['javaPath','gamePath'])if(typeof next[key]!=='string')throw Error('Ruta de ajustes inválida.');fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(next,null,2));const fd=fs.openSync(tmp,'r+');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fs.existsSync(this.file))fs.copyFileSync(this.file,this.file+'.previous');fs.renameSync(tmp,this.file);this.data=next;return {...next};}
 migrate(legacy,root){if(fs.existsSync(this.file))return {...this.data};const username=validName(legacy.username)&&legacy.username!=='Jugador'?legacy.username:'';const existing=fs.existsSync(path.join(root,'options.txt'));return this.save({username,ram:legacy.ram||6,javaPath:legacy.javaPath||'',gamePath:root,graphicsMode:existing?'vanilla':'optimized',graphicsPending:!existing});}
}
module.exports={Settings,validName,MODES};
