package net.tecnihardcore;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class BossCombatTest {
 @Test void threeDistinctRepertoiresAndHealthBars(){assertEquals(1900,BossCombat.health(1)+BossCombat.health(2)+BossCombat.health(3));assertEquals(1000,BossCombat.health(3));assertEquals(3,BossCombat.pool(1).length);assertEquals(4,BossCombat.pool(2).length);assertEquals(5,BossCombat.pool(3).length);for(int phase=1;phase<=3;phase++)for(int skill:BossCombat.pool(phase)){assertNotEquals(skill,BossCombat.choose(phase,skill,false));assertNotEquals(skill,BossCombat.choose(phase,skill,true));assertTrue(BossCombat.plan(phase,skill).windup()>=14);}}
 @Test void allDelayedReleasesPrecedeCompletion(){assertTrue(BossCombat.plan(2,5).finish()>BossCombat.plan(2,5).windup()+20);assertTrue(BossCombat.plan(3,12).finish()>BossCombat.plan(3,12).windup()+36);var a=BossCombat.plan(1,3);assertTrue(a.volley(a.windup()));assertTrue(a.volley(a.windup()+7));assertFalse(a.volley(a.windup()+14));}
 @Test void reinforcedDamageStillLeavesAnUnenchantedDiamondPlayerAliveAfterOneHit(){for(int phase=1;phase<=3;phase++){float damage=BossCombat.meleeDamage(phase);double afterArmor=damage*(1-Math.max(4,20-damage/4.0)/25);assertTrue(afterArmor>=5&&afterArmor<20);for(int type:BossCombat.pool(phase))assertTrue(BossCombat.damage(type)>0&&BossCombat.damage(type)<=26);}assertEquals(80,BossCombat.transitionTicks(2));assertEquals(120,BossCombat.transitionTicks(3));}
 @Test void distantTargetsCycleThroughEveryFinalRangedAbility(){int previous=8;var seen=new java.util.HashSet<Integer>();for(int i=0;i<6;i++){int next=BossCombat.choose(3,previous,true);assertNotEquals(previous,next);seen.add(next);previous=next;}assertEquals(java.util.Set.of(9,10,12),seen);}
 @Test void cooldownUsesSameActivationAcrossBorderAndExactBoundary(){long used=1_000_000;assertEquals(1000,BossCombat.remaining(used+59_000,used,true));assertEquals(0,BossCombat.remaining(used+60_000,used,true));assertEquals(240_000,BossCombat.remaining(used+60_000,used,false));assertEquals(1000,BossCombat.remaining(used+299_000,used,false));assertEquals(0,BossCombat.remaining(used+300_000,used,false));assertEquals(0,BossCombat.remaining(used,0,false));}
}
