# TecniHardcore managed Simple Voice Chat defaults
config_version=1
onboarding_finished=true
microphone_activation_type=PTT
microphone=
speaker=
muted=false
disabled=false
show_nametag_icons=true
show_hud_icons=true
denoiser=true
automatic_gain_control=true
