const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {Settings}=require('../settings'),graphics=require('../graphics'),folders=require('../game-folder');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tecni24-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('moving the executable does not change the saved Minecraft identity',t=>{const dir=temp(t),s=new Settings(dir);s.migrate({username:'Amigo_D',ram:4},path.join(dir,'game'));s.save({gamePath:'D:\\Minecraft'});assert.equal(new Settings(dir).data.username,'Amigo_D');assert.equal(new Settings(dir).data.gamePath,'D:\\Minecraft');assert.throws(()=>s.save({username:'12345678-ffff-eeee-aaaa-123456789012'}));});
test('an inherited default does not silently become an identity',t=>{const dir=temp(t),s=new Settings(dir);assert.equal(s.migrate({username:'Jugador'},path.join(dir,'game')).username,'');assert.equal(s.save({username:'Jugador'}).username,'Jugador');});
test('a damaged preferences file is preserved instead of resetting the player',t=>{const dir=temp(t);fs.writeFileSync(path.join(dir,'settings.json'),'{broken');assert.throws(()=>new Settings(dir));assert.equal(fs.readFileSync(path.join(dir,'settings.json'),'utf8'),'{broken');});
test('graphics changes preserve controls, sound, lives, RAM and simulation',async t=>{const dir=temp(t),root=path.join(dir,'game');fs.mkdirSync(root);const original='key_key.attack:key.mouse.left\nsoundCategory_master:0.3\nguiScale:4\nsimulationDistance:8\nresourcePacks:["official"]\n';fs.writeFileSync(path.join(root,'options.txt'),original);await graphics.apply(root,'ultra-optimized',dir);let result=fs.readFileSync(path.join(root,'options.txt'),'utf8');for(const line of original.trim().split('\n'))assert.ok(result.includes(line));assert.ok(result.includes('renderDistance:6'));await graphics.apply(root,'vanilla',dir);assert.ok(fs.readFileSync(path.join(root,'config','iris.properties'),'utf8').includes('enableShaders=false'));});
test('a failed shader download does not pretend to activate quality',async t=>{const dir=temp(t),root=path.join(dir,'game');fs.mkdirSync(root);fs.writeFileSync(path.join(root,'options.txt'),'renderDistance:8\n');fs.writeFileSync(path.join(dir,'shaders-download.json'),JSON.stringify({name:'original.zip',url:'https://cdn.modrinth.com/example',bytes:2,sha256:'bad',sha512:'bad'}));await assert.rejects(()=>graphics.apply(root,'quality',dir,()=>{},async()=>({ok:false})));assert.equal(fs.readFileSync(path.join(root,'options.txt'),'utf8'),'renderDistance:8\n');assert.equal(fs.existsSync(path.join(root,'config','iris.properties')),false);});
test('verified game transfer retains the original and rejects nested/occupied destinations',async t=>{const dir=temp(t),source=path.join(dir,'old'),target=path.join(dir,'new');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'options.txt'),'owner preferences');await folders.transfer(source,target);assert.equal(fs.readFileSync(path.join(target,'options.txt'),'utf8'),'owner preferences');assert.ok(fs.existsSync(path.join(source,'options.txt')));assert.throws(()=>folders.safe(source,path.join(source,'nested')));await assert.rejects(()=>folders.transfer(source,target));});
